package edu.iu.uis.hr.tk.timesheet.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:43 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;
import java.util.Collection;

import edu.iu.uis.hr.Timestamp;
import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;
import edu.iu.uis.hr.entity.logic.Utility;
import edu.iu.uis.hr.tk.entity.Translate;

public abstract class AbstractClockLog extends AbstractPersistentDatabaseEntity {
	private String universityId;
	private BigDecimal employeeRecord;
	private BigDecimal workArea;
	private BigDecimal task;
	private Timestamp clockTime;
	private String action;
	private String ipAddress;
	private String userUniversityId;
	private Timestamp timestamp;
	private String timeZone;
	private Collection translates;

	public AbstractClockLog() {
		super();
	}

	public Collection getTranslates() {
		return translates;
	}

	public void setTranslates(Collection translates) {
		if (translates != null) {
			this.translates = translates;
		}
	}

	public Translate getTranslate() {
		if (Utility.hasValue(getTranslates())) {
			return (Translate)getTranslates().iterator().next();
		} else {
			return new Translate();
		}
	}

	public String getUniversityId() {
		return universityId;
	}

	public void setUniversityId(String universityId) {
		this.universityId = universityId;
	}

	public BigDecimal getEmployeeRecord() {
		return employeeRecord;
	}

	public void setEmployeeRecord(BigDecimal employeeRecord) {
		this.employeeRecord = employeeRecord;
	}

	public BigDecimal getWorkArea() {
		return workArea;
	}

	public void setWorkArea(BigDecimal workArea) {
		this.workArea = workArea;
	}

	public BigDecimal getTask() {
		return task;
	}

	public void setTask(BigDecimal task) {
		this.task = task;
	}

	public Timestamp getClockTime() {
		return clockTime;
	}

	public void setClockTime(Timestamp clockTime) {
		this.clockTime = clockTime;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getIpAddress() {
		return ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getUserUniversityId() {
		return userUniversityId;
	}

	public void setUserUniversityId(String userUniversityId) {
		this.userUniversityId = userUniversityId;
	}

	public Timestamp getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Timestamp timestamp) {
		this.timestamp = timestamp;
	}

	public String getTimeZone() {
		return timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

}