package edu.iu.uis.hr.tk.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:42 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;
import java.util.Date;

import edu.iu.uis.hr.EffectiveDatedObject;
import edu.iu.uis.hr.EffectiveSequencedObject;
import edu.iu.uis.hr.EffectiveStatusedObject;
import edu.iu.uis.hr.Timestamp;
import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractTranslate extends AbstractPersistentDatabaseEntity implements EffectiveDatedObject, EffectiveSequencedObject, EffectiveStatusedObject {
	private String fieldName;
	private String fieldValue;
	private Date effectiveDate;
	private BigDecimal effectiveSequence;
	private boolean active;
	private String description;
	private String userUniversityId;
	private Timestamp timestamp;

	public AbstractTranslate() {
		super();
	}

	public String getFieldName() {
		return fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public String getFieldValue() {
		return fieldValue;
	}

	public void setFieldValue(String fieldValue) {
		this.fieldValue = fieldValue;
	}

	public Date getEffectiveDate() {
		return effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public BigDecimal getEffectiveSequence() {
		return effectiveSequence;
	}

	public void setEffectiveSequence(BigDecimal effectiveSequence) {
		this.effectiveSequence = effectiveSequence;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUserUniversityId() {
		return userUniversityId;
	}

	public void setUserUniversityId(String userUniversityId) {
		this.userUniversityId = userUniversityId;
	}

	public Timestamp getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Timestamp timestamp) {
		this.timestamp = timestamp;
	}

}