package edu.iu.uis.hr.tk.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:43 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.util.Collection;

import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractUserPreference extends AbstractPersistentDatabaseEntity {
	private String universityId;
	private String preferenceCode;
	private Collection preferences;

	public AbstractUserPreference() {
		super();
	}

	public Collection getPreferences() {
		return preferences;
	}

	public void setPreferences(Collection preferences) {
		if (preferences != null) {
			this.preferences = preferences;
		}
	}

	public String getUniversityId() {
		return universityId;
	}

	public void setUniversityId(String universityId) {
		this.universityId = universityId;
	}

	public String getPreferenceCode() {
		return preferenceCode;
	}

	public void setPreferenceCode(String preferenceCode) {
		this.preferenceCode = preferenceCode;
	}

}