package edu.iu.uis.hr.tk.timesheet.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:43 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;

import edu.iu.uis.hr.Timestamp;
import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractTimeBlockHistory extends AbstractPersistentDatabaseEntity {
	private BigDecimal recordId;
	private String documentId;
	private BigDecimal employeeRecord;
	private BigDecimal workArea;
	private BigDecimal task;
	private String earnCode;
	private Timestamp beginTime;
	private Timestamp endTime;
	private boolean createdByClock;
	private BigDecimal hours;
	private String overtimeEarnCode;
	private BigDecimal overtimeHours;
	private String shiftEarnCode;
	private BigDecimal shiftHours;
	private String premiumEarnCode;
	private BigDecimal premiumHours;
	private String actionHistory;
	private String modifiedByUniversityId;
	private String userUniversityId;
	private Timestamp timestampOriginal;
	private Timestamp timestamp;
	private String beginTsTz;
	private String endTsTz;
	private String timestampTz;
	private String timestampOriginalTz;

	public AbstractTimeBlockHistory() {
		super();
	}

	public BigDecimal getRecordId() {
		return recordId;
	}

	public void setRecordId(BigDecimal recordId) {
		this.recordId = recordId;
	}

	public String getDocumentId() {
		return documentId;
	}

	public void setDocumentId(String documentId) {
		this.documentId = documentId;
	}

	public BigDecimal getEmployeeRecord() {
		return employeeRecord;
	}

	public void setEmployeeRecord(BigDecimal employeeRecord) {
		this.employeeRecord = employeeRecord;
	}

	public BigDecimal getWorkArea() {
		return workArea;
	}

	public void setWorkArea(BigDecimal workArea) {
		this.workArea = workArea;
	}

	public BigDecimal getTask() {
		return task;
	}

	public void setTask(BigDecimal task) {
		this.task = task;
	}

	public String getEarnCode() {
		return earnCode;
	}

	public void setEarnCode(String earnCode) {
		this.earnCode = earnCode;
	}

	public Timestamp getBeginTime() {
		return beginTime;
	}

	public void setBeginTime(Timestamp beginTime) {
		this.beginTime = beginTime;
	}

	public Timestamp getEndTime() {
		return endTime;
	}

	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}

	public boolean isCreatedByClock() {
		return createdByClock;
	}

	public void setCreatedByClock(boolean createdByClock) {
		this.createdByClock = createdByClock;
	}

	public BigDecimal getHours() {
		return hours;
	}

	public void setHours(BigDecimal hours) {
		this.hours = hours;
	}

	public String getOvertimeEarnCode() {
		return overtimeEarnCode;
	}

	public void setOvertimeEarnCode(String overtimeEarnCode) {
		this.overtimeEarnCode = overtimeEarnCode;
	}

	public BigDecimal getOvertimeHours() {
		return overtimeHours;
	}

	public void setOvertimeHours(BigDecimal overtimeHours) {
		this.overtimeHours = overtimeHours;
	}

	public String getShiftEarnCode() {
		return shiftEarnCode;
	}

	public void setShiftEarnCode(String shiftEarnCode) {
		this.shiftEarnCode = shiftEarnCode;
	}

	public BigDecimal getShiftHours() {
		return shiftHours;
	}

	public void setShiftHours(BigDecimal shiftHours) {
		this.shiftHours = shiftHours;
	}

	public String getPremiumEarnCode() {
		return premiumEarnCode;
	}

	public void setPremiumEarnCode(String premiumEarnCode) {
		this.premiumEarnCode = premiumEarnCode;
	}

	public BigDecimal getPremiumHours() {
		return premiumHours;
	}

	public void setPremiumHours(BigDecimal premiumHours) {
		this.premiumHours = premiumHours;
	}

	public String getActionHistory() {
		return actionHistory;
	}

	public void setActionHistory(String actionHistory) {
		this.actionHistory = actionHistory;
	}

	public String getModifiedByUniversityId() {
		return modifiedByUniversityId;
	}

	public void setModifiedByUniversityId(String modifiedByUniversityId) {
		this.modifiedByUniversityId = modifiedByUniversityId;
	}

	public String getUserUniversityId() {
		return userUniversityId;
	}

	public void setUserUniversityId(String userUniversityId) {
		this.userUniversityId = userUniversityId;
	}

	public Timestamp getTimestampOriginal() {
		return timestampOriginal;
	}

	public void setTimestampOriginal(Timestamp timestampOriginal) {
		this.timestampOriginal = timestampOriginal;
	}

	public Timestamp getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Timestamp timestamp) {
		this.timestamp = timestamp;
	}

	public String getBeginTsTz() {
		return beginTsTz;
	}

	public void setBeginTsTz(String beginTsTz) {
		this.beginTsTz = beginTsTz;
	}

	public String getEndTsTz() {
		return endTsTz;
	}

	public void setEndTsTz(String endTsTz) {
		this.endTsTz = endTsTz;
	}

	public String getTimestampTz() {
		return timestampTz;
	}

	public void setTimestampTz(String timestampTz) {
		this.timestampTz = timestampTz;
	}

	public String getTimestampOriginalTz() {
		return timestampOriginalTz;
	}

	public void setTimestampOriginalTz(String timestampOriginalTz) {
		this.timestampOriginalTz = timestampOriginalTz;
	}

}