--supp workflow - new branch
update krim_rsp_t a
set nm = replace(nm, 'Dept', 'Dept Chair' )
where rsp_id in ( '11139', '11142', '11149', '11152' );
update krim_rsp_attr_data_t a
set attr_val = replace(attr_val, 'Dept', 'DeptChair' )
where rsp_id in ( '11139', '11142', '11149', '11152' )
and kim_attr_defn_id = 16;

SET DEFINE OFF;
INSERT INTO krim_rsp_t (rsp_id, obj_id, ver_nbr, rsp_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_rsp_id_s.nextval, sys_guid(), '1', (SELECT rsp_tmpl_id FROM krim_rsp_tmpl_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Review' AND kim_typ_id = (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information')), 'EDO', 'Suppl Tenure Dept ACK', '', 'Y');
INSERT INTO krim_rsp_t (rsp_id, obj_id, ver_nbr, rsp_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_rsp_id_s.nextval, sys_guid(), '1', (SELECT rsp_tmpl_id FROM krim_rsp_tmpl_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Review' AND kim_typ_id = (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information')), 'EDO', 'Suppl Tenure Dept FYI', '', 'Y');
INSERT INTO krim_rsp_t (rsp_id, obj_id, ver_nbr, rsp_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_rsp_id_s.nextval, sys_guid(), '1', (SELECT rsp_tmpl_id FROM krim_rsp_tmpl_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Review' AND kim_typ_id = (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information')), 'EDO', 'Suppl Promotion Dept ACK', '', 'Y');
INSERT INTO krim_rsp_t (rsp_id, obj_id, ver_nbr, rsp_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_rsp_id_s.nextval, sys_guid(), '1', (SELECT rsp_tmpl_id FROM krim_rsp_tmpl_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Review' AND kim_typ_id = (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information')), 'EDO', 'Suppl Promotion Dept FYI', '', 'Y');

SET DEFINE OFF;
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept ACK'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'documentTypeName'), 'TenureSupplementalProcessDocument');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept FYI'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'documentTypeName'), 'TenureSupplementalProcessDocument');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept ACK'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'required'), 'true');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept FYI'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'required'), 'true');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept ACK'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'actionDetailsAtRoleMemberLevel'), 'true');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept FYI'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'actionDetailsAtRoleMemberLevel'), 'true');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept ACK'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'routeNodeName'), 'supplDeptLevelAck');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept FYI'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'routeNodeName'), 'supplDeptLevel');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept ACK'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'documentTypeName'), 'PromotionSupplementalProcessDocument');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept FYI'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'documentTypeName'), 'PromotionSupplementalProcessDocument');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept ACK'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'required'), 'true');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept FYI'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'required'), 'true');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept ACK'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'actionDetailsAtRoleMemberLevel'), 'true');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept FYI'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'actionDetailsAtRoleMemberLevel'), 'true');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept ACK'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'routeNodeName'), 'supplDeptLevelAck');
INSERT INTO krim_rsp_attr_data_t (attr_data_id, obj_id, ver_nbr, rsp_id, kim_typ_id, kim_attr_defn_id, attr_val) VALUES (krim_attr_data_id_s.nextval, sys_guid(), '1', (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept FYI'), (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'Document Type, Routing Node & Action Information'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'KR-WKFLW' AND nm = 'routeNodeName'), 'supplDeptLevel');

SET DEFINE OFF;
INSERT INTO krim_role_rsp_t (role_rsp_id, obj_id, ver_nbr, role_id, rsp_id, actv_ind) VALUES (krim_role_rsp_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1'), (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept FYI'), 'Y');
INSERT INTO krim_role_rsp_t (role_rsp_id, obj_id, ver_nbr, role_id, rsp_id, actv_ind) VALUES (krim_role_rsp_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1'), (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept ACK'), 'Y');
INSERT INTO krim_role_rsp_t (role_rsp_id, obj_id, ver_nbr, role_id, rsp_id, actv_ind) VALUES (krim_role_rsp_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1'), (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept FYI'), 'Y');
INSERT INTO krim_role_rsp_t (role_rsp_id, obj_id, ver_nbr, role_id, rsp_id, actv_ind) VALUES (krim_role_rsp_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1'), (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept ACK'), 'Y');

SET DEFINE OFF;
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLCRIN')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLTHTR')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLFINS')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLELPS')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLISTE')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLLGED')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLCRIN')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept FYI')), 'F', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLTHTR')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept FYI')), 'F', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLFINS')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept FYI')), 'F', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLELPS')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept FYI')), 'F', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLISTE')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept FYI')), 'F', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-TENURE-BLLGED')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_TENURE_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Tenure Dept FYI')), 'F', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLCRIN')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLTHTR')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLFINS')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLELPS')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLISTE')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLLGED')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept ACK')), 'A', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLCRIN')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept FYI')), 'F', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLTHTR')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept FYI')), 'F', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLFINS')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept FYI')), 'F', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLELPS')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept FYI')), 'F', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLISTE')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept FYI')), 'F', '1', 'F', 'Y');
INSERT INTO krim_role_rsp_actn_t (role_rsp_actn_id, obj_id, ver_nbr, role_mbr_id, role_rsp_id, actn_typ_cd, priority_nbr, actn_plcy_cd, frc_actn) VALUES (krim_role_rsp_actn_id_s.nextval, sys_guid(), '1', (SELECT role_mbr_id FROM krim_role_mbr_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND mbr_typ_cd = 'G' AND mbr_id = (SELECT grp_id FROM krim_grp_t WHERE nmspc_cd = 'EDO' AND grp_nm = 'EDO-LEVEL1-APPROVE-PROMOTION-BLLGED')), (SELECT role_rsp_id FROM krim_role_rsp_t WHERE role_id = (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_COMMITTEE_CHAIR_PROMOTION_LEVEL1') AND rsp_id = (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Suppl Promotion Dept FYI')), 'F', '1', 'F', 'Y');

---secondary unit role and permissions ---

INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_SECOND_UNIT_REVIEWER', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'DossierID'), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_SECOND_UNIT_REVIEWER'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Login Permission' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'Login')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_SECOND_UNIT_REVIEWER'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use all screens' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_SECOND_UNIT_REVIEWER'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use Edossier Reviewer Screen' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');

INSERT INTO krim_perm_tmpl_t (perm_tmpl_id, obj_id, ver_nbr, nmspc_cd, nm, desc_txt, kim_typ_id, actv_ind) VALUES (krim_perm_tmpl_id_s.nextval, sys_guid(), '1', 'EDO', 'Upload Secondary Unit Letter', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'DossierID'), 'Y');
INSERT INTO krim_perm_t (perm_id, obj_id, ver_nbr, perm_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_perm_id_s.nextval, sys_guid(), '1', (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'Upload Secondary Unit Letter'), 'EDO', 'Upload Secondary Unit Letter', '', 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_SECOND_UNIT_REVIEWER'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Upload Secondary Unit Letter' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'Upload Secondary Unit Letter')), 'Y');

-- check list sign off role ----
INSERT INTO krim_typ_t (kim_typ_id, obj_id, ver_nbr, nm, srvc_nm, actv_ind, nmspc_cd) VALUES (krim_typ_id_s.nextval, sys_guid(), '1', 'Check List Sign Off Role', '{EDO}edoCheckListSignOffRoleTypeService', 'Y', 'EDO');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'a', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Check List Sign Off Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoDepartmentId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'b', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Check List Sign Off Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoSchoolId'), 'Y');
INSERT INTO krim_typ_attr_t (kim_typ_attr_id, obj_id, ver_nbr, sort_cd, kim_typ_id, kim_attr_defn_id, actv_ind) VALUES (krim_typ_attr_id_s.nextval, sys_guid(), '1', 'c', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Check List Sign Off Role'), (SELECT kim_attr_defn_id FROM krim_attr_defn_t WHERE nmspc_cd = 'EDO' AND nm = 'edoDossierID'), 'Y');

INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_CHECK_LIST_SIGN_OFF', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Check List Sign Off Role'), 'Y');

INSERT INTO krim_perm_tmpl_t (perm_tmpl_id, obj_id, ver_nbr, nmspc_cd, nm, desc_txt, kim_typ_id, actv_ind) VALUES (krim_perm_tmpl_id_s.nextval, sys_guid(), '1', 'EDO', 'Check List Sign Off', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'KUALI' AND nm = 'Default'), 'Y');
INSERT INTO krim_perm_t (perm_id, obj_id, ver_nbr, perm_tmpl_id, nmspc_cd, nm, desc_txt, actv_ind) VALUES (krim_perm_id_s.nextval, sys_guid(), '1', (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'Check List Sign Off'), 'EDO', 'Check List Sign Off', '', 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CHECK_LIST_SIGN_OFF'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Check List Sign Off' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'Check List Sign Off')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CHECK_LIST_SIGN_OFF'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use Edossier Reviewer Screen' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CHECK_LIST_SIGN_OFF'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Login Permission' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'Login')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CHECK_LIST_SIGN_OFF'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use all screens' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');

INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_CHECK_LIST_SIGN_OFF'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Submit Dossier' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-SYS' AND nm = 'Initiate Document')), 'Y');



-- Level2 and Level4 FYI roles --

This is the sql that has to be run for creation of the roles, responsibilities etc

INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_FYI_REVIEWER_TENURE_LEVEL2', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Department'), 'Y');
INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_FYI_REVIEWER_PROMOTION_LEVEL2', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'Department'), 'Y');
INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_FYI_REVIEWER_TENURE_LEVEL4', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'School'), 'Y');
INSERT INTO krim_role_t (role_id, obj_id, ver_nbr, role_nm, nmspc_cd, desc_txt, kim_typ_id, actv_ind) VALUES (krim_role_id_s.nextval, sys_guid(), '1', 'EDO_FYI_REVIEWER_PROMOTION_LEVEL4', 'EDO', '', (SELECT kim_typ_id FROM krim_typ_t WHERE nmspc_cd = 'EDO' AND nm = 'School'), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL2'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use all screens' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL2'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use all screens' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL2'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use Edossier Reviewer Screen' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL2'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use Edossier Reviewer Screen' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL2'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Login Permission' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'Login')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL2'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Login Permission' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'Login')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL2'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 1' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL2'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 1' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL2'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 2' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL2'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 2' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use all screens' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use all screens' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use Edossier Reviewer Screen' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Use Edossier Reviewer Screen' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'KR-NS' AND nm = 'Use Screen')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Login Permission' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'Login')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'Login Permission' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'Login')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 1' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 1' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 2' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 2' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 3' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 3' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 4' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_perm_t (role_perm_id, obj_id, ver_nbr, role_id, perm_id, actv_ind) VALUES (krim_role_perm_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL4'), (SELECT perm_id FROM krim_perm_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record Level 4' AND perm_tmpl_id = (SELECT perm_tmpl_id FROM krim_perm_tmpl_t WHERE nmspc_cd = 'EDO' AND nm = 'View Vote Record')), 'Y');
INSERT INTO krim_role_rsp_t (role_rsp_id, obj_id, ver_nbr, role_id, rsp_id, actv_ind) VALUES (krim_role_rsp_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL2'), (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Tenure Level2'), 'Y');
INSERT INTO krim_role_rsp_t (role_rsp_id, obj_id, ver_nbr, role_id, rsp_id, actv_ind) VALUES (krim_role_rsp_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL2'), (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Promotion Level2'), 'Y');
INSERT INTO krim_role_rsp_t (role_rsp_id, obj_id, ver_nbr, role_id, rsp_id, actv_ind) VALUES (krim_role_rsp_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_TENURE_LEVEL4'), (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Tenure Level4'), 'Y');
INSERT INTO krim_role_rsp_t (role_rsp_id, obj_id, ver_nbr, role_id, rsp_id, actv_ind) VALUES (krim_role_rsp_id_s.nextval, sys_guid(), '1', (SELECT role_id FROM krim_role_t WHERE nmspc_cd = 'EDO' AND role_nm = 'EDO_FYI_REVIEWER_PROMOTION_LEVEL4'), (SELECT rsp_id FROM krim_rsp_t WHERE nmspc_cd = 'EDO' AND nm = 'Promotion Level4'), 'Y');











