package edu.iu.uis.hr.tk.employee.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:42 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.util.Date;

import edu.iu.uis.hr.EffectiveDatedObject;
import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractEarningsAccrual extends AbstractPersistentDatabaseEntity implements EffectiveDatedObject {
	private String earnCode;
	private Date effectiveDate;
	private String planType;
	private boolean addHoursTaken;

	public AbstractEarningsAccrual() {
		super();
	}

	public String getEarnCode() {
		return earnCode;
	}

	public void setEarnCode(String earnCode) {
		this.earnCode = earnCode;
	}

	public Date getEffectiveDate() {
		return effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public String getPlanType() {
		return planType;
	}

	public void setPlanType(String planType) {
		this.planType = planType;
	}

	public boolean isAddHoursTaken() {
		return addHoursTaken;
	}

	public void setAddHoursTaken(boolean addHoursTaken) {
		this.addHoursTaken = addHoursTaken;
	}

}