package edu.iu.uis.hr.tk.report.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:43 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;
import java.util.Date;

import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;
import edu.iu.uis.hr.tk.TKServiceLocator;

public abstract class AbstractBatchMessage extends AbstractPersistentDatabaseEntity {
	private BigDecimal messageId;
	private String processName;
	private Date processDate;
	private String documentId;
	private String universityId;
	private String message;

	public AbstractBatchMessage() {
		super();
	}

//	public BigDecimal getMessageId() {
//		return messageId;
//	}

	public void setMessageId(BigDecimal messageId) {
		this.messageId = messageId;
	}

	public String getProcessName() {
		return processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	public Date getProcessDate() {
		return processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	public String getDocumentId() {
		return TKServiceLocator.getBatchMessageService().formatDocHandler(this.documentId);
		//return documentId;
	}

	public void setDocumentId(String documentId) {
		this.documentId = documentId;
	}

	public String getUniversityId() {
		return universityId;
	}

	public void setUniversityId(String universityId) {
		this.universityId = universityId;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}