package edu.iu.uis.hr.tk.job.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:42 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;
import java.util.Collection;
import java.util.Date;

import edu.iu.uis.hr.EffectiveDatedObject;
import edu.iu.uis.hr.EffectiveSequencedObject;
import edu.iu.uis.hr.SetControlValuedObject;
import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractJob extends AbstractPersistentDatabaseEntity implements EffectiveDatedObject, EffectiveSequencedObject, SetControlValuedObject {
	private String universityId;
	private BigDecimal employeeRecord;
	private Date effectiveDate;
	private BigDecimal effectiveSequence;
	private String action;
	private String actionReason;
	private String position;
	private String company;
	private String businessUnit;
	private String department;
	private String location;
	private String jobcode;
	private String salaryPlan;
	private String grade;
	private BigDecimal standardHours;
	private String employeeType;
	private String paygroup;
	private BigDecimal compensationRate;
	private BigDecimal fte;
	private String employeeStatus;
	private String employeeClass;
	private String jobIndicator;
	private String earnsDistributionType;
	private Collection earningsDistributions;
	private Collection assignments;

	public AbstractJob() {
		super();
	}

	public Collection getEarningsDistributions() {
		return earningsDistributions;
	}

	public void setEarningsDistributions(Collection earningsDistributions) {
		if (earningsDistributions != null) {
			this.earningsDistributions = earningsDistributions;
		}
	}

	public Collection getAssignments() {
		return assignments;
	}

	public void setAssignments(Collection assignments) {
		if (assignments != null) {
			this.assignments = assignments;
		}
	}

	public String getUniversityId() {
		return universityId;
	}

	public void setUniversityId(String universityId) {
		this.universityId = universityId;
	}

	public BigDecimal getEmployeeRecord() {
		return employeeRecord;
	}

	public void setEmployeeRecord(BigDecimal employeeRecord) {
		this.employeeRecord = employeeRecord;
	}

	public Date getEffectiveDate() {
		return effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public BigDecimal getEffectiveSequence() {
		return effectiveSequence;
	}

	public void setEffectiveSequence(BigDecimal effectiveSequence) {
		this.effectiveSequence = effectiveSequence;
	}

	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getActionReason() {
		return actionReason;
	}

	public void setActionReason(String actionReason) {
		this.actionReason = actionReason;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getBusinessUnit() {
		return businessUnit;
	}

	public void setBusinessUnit(String businessUnit) {
		this.businessUnit = businessUnit;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getJobcode() {
		return jobcode;
	}

	public void setJobcode(String jobcode) {
		this.jobcode = jobcode;
	}

	public String getSalaryPlan() {
		return salaryPlan;
	}

	public void setSalaryPlan(String salaryPlan) {
		this.salaryPlan = salaryPlan;
	}

	public String getGrade() {
		return grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public BigDecimal getStandardHours() {
		return standardHours;
	}

	public void setStandardHours(BigDecimal standardHours) {
		this.standardHours = standardHours;
	}

	public String getEmployeeType() {
		return employeeType;
	}

	public void setEmployeeType(String employeeType) {
		this.employeeType = employeeType;
	}

	public String getPaygroup() {
		return paygroup;
	}

	public void setPaygroup(String paygroup) {
		this.paygroup = paygroup;
	}

	public BigDecimal getCompensationRate() {
		return compensationRate;
	}

	public void setCompensationRate(BigDecimal compensationRate) {
		this.compensationRate = compensationRate;
	}

	public BigDecimal getFte() {
		return fte;
	}

	public void setFte(BigDecimal fte) {
		this.fte = fte;
	}

	public String getEmployeeStatus() {
		return employeeStatus;
	}

	public void setEmployeeStatus(String employeeStatus) {
		this.employeeStatus = employeeStatus;
	}

	public String getEmployeeClass() {
		return employeeClass;
	}

	public void setEmployeeClass(String employeeClass) {
		this.employeeClass = employeeClass;
	}

	public String getJobIndicator() {
		return jobIndicator;
	}

	public void setJobIndicator(String jobIndicator) {
		this.jobIndicator = jobIndicator;
	}

	public String getEarnsDistributionType() {
		return earnsDistributionType;
	}

	public void setEarnsDistributionType(String earnsDistributionType) {
		this.earnsDistributionType = earnsDistributionType;
	}

}