package edu.iu.uis.hr.tk.employee.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Jan 25 13:10:01 EST 2008
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractEmployee extends AbstractPersistentDatabaseEntity {
	private String universityId;

	public AbstractEmployee() {
		super();
	}

	public String getUniversityId() {
		return universityId;
	}

	public void setUniversityId(String universityId) {
		this.universityId = universityId;
	}

}