package edu.iu.uis.hr.tk.extract.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:42 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;
import java.util.Date;

import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractPayEarnings extends AbstractPersistentDatabaseEntity {
	private String company;
	private String paygroup;
	private Date payEndDate;
	private boolean offCycle;
	private BigDecimal pageNumber;
	private BigDecimal lineNumber;
	private BigDecimal additionalPayLineNumber;
	private String universityId;
	private BigDecimal employeeRecord;
	private Date earnsEndDate;
	private Date earnsBeginDate;
	private BigDecimal hourlyRate;
	private String earnCodeRegularHours;
	private String earnCodeOvertimeHours;
	private BigDecimal regularHours;
	private BigDecimal overtimeHours;
	private String ficaStatus;
	private String singleCheckUse;

	public AbstractPayEarnings() {
		super();
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getPaygroup() {
		return paygroup;
	}

	public void setPaygroup(String paygroup) {
		this.paygroup = paygroup;
	}

	public Date getPayEndDate() {
		return payEndDate;
	}

	public void setPayEndDate(Date payEndDate) {
		this.payEndDate = payEndDate;
	}

	public boolean isOffCycle() {
		return offCycle;
	}

	public void setOffCycle(boolean offCycle) {
		this.offCycle = offCycle;
	}

	public BigDecimal getPageNumber() {
		return pageNumber;
	}

	public void setPageNumber(BigDecimal pageNumber) {
		this.pageNumber = pageNumber;
	}

	public BigDecimal getLineNumber() {
		return lineNumber;
	}

	public void setLineNumber(BigDecimal lineNumber) {
		this.lineNumber = lineNumber;
	}

	public BigDecimal getAdditionalPayLineNumber() {
		return additionalPayLineNumber;
	}

	public void setAdditionalPayLineNumber(BigDecimal additionalPayLineNumber) {
		this.additionalPayLineNumber = additionalPayLineNumber;
	}

	public String getUniversityId() {
		return universityId;
	}

	public void setUniversityId(String universityId) {
		this.universityId = universityId;
	}

	public BigDecimal getEmployeeRecord() {
		return employeeRecord;
	}

	public void setEmployeeRecord(BigDecimal employeeRecord) {
		this.employeeRecord = employeeRecord;
	}

	public Date getEarnsEndDate() {
		return earnsEndDate;
	}

	public void setEarnsEndDate(Date earnsEndDate) {
		this.earnsEndDate = earnsEndDate;
	}

	public Date getEarnsBeginDate() {
		return earnsBeginDate;
	}

	public void setEarnsBeginDate(Date earnsBeginDate) {
		this.earnsBeginDate = earnsBeginDate;
	}

	public BigDecimal getHourlyRate() {
		return hourlyRate;
	}

	public void setHourlyRate(BigDecimal hourlyRate) {
		this.hourlyRate = hourlyRate;
	}

	public String getEarnCodeRegularHours() {
		return earnCodeRegularHours;
	}

	public void setEarnCodeRegularHours(String earnCodeRegularHours) {
		this.earnCodeRegularHours = earnCodeRegularHours;
	}

	public String getEarnCodeOvertimeHours() {
		return earnCodeOvertimeHours;
	}

	public void setEarnCodeOvertimeHours(String earnCodeOvertimeHours) {
		this.earnCodeOvertimeHours = earnCodeOvertimeHours;
	}

	public BigDecimal getRegularHours() {
		return regularHours;
	}

	public void setRegularHours(BigDecimal regularHours) {
		this.regularHours = regularHours;
	}

	public BigDecimal getOvertimeHours() {
		return overtimeHours;
	}

	public void setOvertimeHours(BigDecimal overtimeHours) {
		this.overtimeHours = overtimeHours;
	}

	public String getFicaStatus() {
		return ficaStatus;
	}

	public void setFicaStatus(String ficaStatus) {
		this.ficaStatus = ficaStatus;
	}

	public String getSingleCheckUse() {
		return singleCheckUse;
	}

	public void setSingleCheckUse(String singleCheckUse) {
		this.singleCheckUse = singleCheckUse;
	}

}