
/*
 * 
 */

package tkmobileservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-11-22T12:37:54.999+05:30
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "tkMobileService", 
                  wsdlLocation = "http://ci.kpme.kuali.org:7080/tk-stg/remoting/tkMobileService?wsdl",
                  targetNamespace = "tkMobileService") 
public class TkMobileService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("tkMobileService", "tkMobileService");
    public final static QName TkMobileServicePort = new QName("tkMobileService", "TkMobileServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://ci.kpme.kuali.org:7080/tk-stg/remoting/tkMobileService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TkMobileService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ci.kpme.kuali.org:7080/tk-stg/remoting/tkMobileService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TkMobileService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TkMobileService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TkMobileService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TkMobileService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TkMobileService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TkMobileService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TkMobileService
     */
    @WebEndpoint(name = "TkMobileServicePort")
    public org.kuali.hr.time.mobile.service.TkMobileService getTkMobileServicePort() {
        return super.getPort(TkMobileServicePort, org.kuali.hr.time.mobile.service.TkMobileService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TkMobileService
     */
    @WebEndpoint(name = "TkMobileServicePort")
    public org.kuali.hr.time.mobile.service.TkMobileService getTkMobileServicePort(WebServiceFeature... features) {
        return super.getPort(TkMobileServicePort, org.kuali.hr.time.mobile.service.TkMobileService.class, features);
    }

}
