package edu.iu.uis.hr.tk.rule.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:42 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;
import java.util.Date;

import edu.iu.uis.hr.EffectiveDatedObject;
import edu.iu.uis.hr.EffectiveSequencedObject;
import edu.iu.uis.hr.EffectiveStatusedObject;
import edu.iu.uis.hr.Time;
import edu.iu.uis.hr.Timestamp;
import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractShiftDifferentialRule extends AbstractPersistentDatabaseEntity implements EffectiveDatedObject, EffectiveSequencedObject, EffectiveStatusedObject {
	private String location;
	private String salaryPlan;
	private String grade;
	private Date effectiveDate;
	private BigDecimal effectiveSequence;
	private boolean active;
	private String earnCode;
	private Time beginTime;
	private Time endTime;
	private BigDecimal minHours;
	private boolean applicableToSunday;
	private boolean applicableToMonday;
	private boolean applicableToTuesday;
	private boolean applicableToWednesday;
	private boolean applicableToThursday;
	private boolean applicableToFriday;
	private boolean applicableToSaturday;
	private BigDecimal maxGap;
	private String userUniversityId;
	private Timestamp timestamp;

	public AbstractShiftDifferentialRule() {
		super();
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getSalaryPlan() {
		return salaryPlan;
	}

	public void setSalaryPlan(String salaryPlan) {
		this.salaryPlan = salaryPlan;
	}

	public String getGrade() {
		return grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public Date getEffectiveDate() {
		return effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public BigDecimal getEffectiveSequence() {
		return effectiveSequence;
	}

	public void setEffectiveSequence(BigDecimal effectiveSequence) {
		this.effectiveSequence = effectiveSequence;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public String getEarnCode() {
		return earnCode;
	}

	public void setEarnCode(String earnCode) {
		this.earnCode = earnCode;
	}

	public Time getBeginTime() {
		return beginTime;
	}

	public void setBeginTime(Time beginTime) {
		this.beginTime = beginTime;
	}

	public Time getEndTime() {
		return endTime;
	}

	public void setEndTime(Time endTime) {
		this.endTime = endTime;
	}

	public BigDecimal getMinHours() {
		return minHours;
	}

	public void setMinHours(BigDecimal minHours) {
		this.minHours = minHours;
	}

	public boolean isApplicableToSunday() {
		return applicableToSunday;
	}

	public void setApplicableToSunday(boolean applicableToSunday) {
		this.applicableToSunday = applicableToSunday;
	}

	public boolean isApplicableToMonday() {
		return applicableToMonday;
	}

	public void setApplicableToMonday(boolean applicableToMonday) {
		this.applicableToMonday = applicableToMonday;
	}

	public boolean isApplicableToTuesday() {
		return applicableToTuesday;
	}

	public void setApplicableToTuesday(boolean applicableToTuesday) {
		this.applicableToTuesday = applicableToTuesday;
	}

	public boolean isApplicableToWednesday() {
		return applicableToWednesday;
	}

	public void setApplicableToWednesday(boolean applicableToWednesday) {
		this.applicableToWednesday = applicableToWednesday;
	}

	public boolean isApplicableToThursday() {
		return applicableToThursday;
	}

	public void setApplicableToThursday(boolean applicableToThursday) {
		this.applicableToThursday = applicableToThursday;
	}

	public boolean isApplicableToFriday() {
		return applicableToFriday;
	}

	public void setApplicableToFriday(boolean applicableToFriday) {
		this.applicableToFriday = applicableToFriday;
	}

	public boolean isApplicableToSaturday() {
		return applicableToSaturday;
	}

	public void setApplicableToSaturday(boolean applicableToSaturday) {
		this.applicableToSaturday = applicableToSaturday;
	}

	public BigDecimal getMaxGap() {
		return maxGap;
	}

	public void setMaxGap(BigDecimal maxGap) {
		this.maxGap = maxGap;
	}

	public String getUserUniversityId() {
		return userUniversityId;
	}

	public void setUserUniversityId(String userUniversityId) {
		this.userUniversityId = userUniversityId;
	}

	public Timestamp getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Timestamp timestamp) {
		this.timestamp = timestamp;
	}

}