CREATE SEQUENCE  TK_MESSAGE_ID_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 143 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  TK_TASK_ID_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1922 CACHE 3 NOORDER  NOCYCLE ;
CREATE SEQUENCE  TK_TIME_BLOCK_HT_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1795 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  TK_WORK_AREA_ID_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 2678 CACHE 3 NOORDER  NOCYCLE ;
  CREATE TABLE TK_APPROACH_OVT_EXCEPTION_T 
   (	EXCEPTION_DT DATE, 
	EXCEPTION_TYPE VARCHAR2(3), 
	EMPLID VARCHAR2(11), 
	EMPL_RCD NUMBER(38,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(38,0), 
	TASK_ID VARCHAR2(7), 
	WEEK_BEGIN_DT DATE, 
	ACTUAL_HOURS NUMBER(3,0), 
	WORK_AREA_ID NUMBER(10,0)
   ) ;
  ALTER TABLE TK_APPROACH_OVT_EXCEPTION_T MODIFY (EXCEPTION_DT NOT NULL ENABLE);
  ALTER TABLE TK_APPROACH_OVT_EXCEPTION_T MODIFY (EXCEPTION_TYPE NOT NULL ENABLE);
  ALTER TABLE TK_APPROACH_OVT_EXCEPTION_T MODIFY (EMPLID NOT NULL ENABLE);
  ALTER TABLE TK_APPROACH_OVT_EXCEPTION_T MODIFY (EMPL_RCD NOT NULL ENABLE);
  ALTER TABLE TK_APPROACH_OVT_EXCEPTION_T MODIFY (EFFDT NOT NULL ENABLE);
  ALTER TABLE TK_APPROACH_OVT_EXCEPTION_T MODIFY (EFFSEQ NOT NULL ENABLE);
  ALTER TABLE TK_APPROACH_OVT_EXCEPTION_T MODIFY (TASK_ID NOT NULL ENABLE);
  ALTER TABLE TK_APPROACH_OVT_EXCEPTION_T MODIFY (WEEK_BEGIN_DT NOT NULL ENABLE);
  ALTER TABLE TK_APPROACH_OVT_EXCEPTION_T MODIFY (ACTUAL_HOURS NOT NULL ENABLE);
  ALTER TABLE TK_APPROACH_OVT_EXCEPTION_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
  ALTER TABLE TK_APPROACH_OVT_EXCEPTION_T ADD CONSTRAINT TK_APPROACH_OVT_EXCEPTION_TP1 PRIMARY KEY (EXCEPTION_DT, EXCEPTION_TYPE, EMPLID, EMPL_RCD, EFFDT, EFFSEQ, TASK_ID, WORK_AREA_ID) ENABLE;

  CREATE TABLE TK_BATCH_MESSAGE_T 
   (	MESSAGE_ID NUMBER(10,0), 
	PROCESS_NAME VARCHAR2(50), 
	PROCESS_DATE DATE, 
	DOCUMENT_ID VARCHAR2(14), 
	EMPLID VARCHAR2(10), 
	MESSAGE VARCHAR2(255)
   ) ;
  CREATE TABLE TK_BREAK_EXCEPTION_T 
   (	EXCEPTION_DT DATE, 
	EXCEPTION_TYPE VARCHAR2(3), 
	EMPLID VARCHAR2(11), 
	EMPL_RCD NUMBER(38,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(38,0), 
	TASK_ID VARCHAR2(7), 
	BLOCK_BEGIN_TS DATE, 
	ACTUAL_MINUTES NUMBER(5,0), 
	RULE_MINUTES NUMBER(5,0), 
	ACTUAL_NUMBER_OF_BREAKS NUMBER(2,0), 
	RULE_NUMBER_OF_BREAKS NUMBER(2,0), 
	WORK_AREA_ID NUMBER(10,0)
   ) ;
  CREATE TABLE TK_BREAK_RL_T 
   (	
  DEPTID VARCHAR2(7), 
	WORK_AREA_ID NUMBER(10,0), 
	EMPLID VARCHAR2(10), 
	EMPL_RCD NUMBER(3,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	BLOCK_HRS NUMBER(2,0), 
	MAX_MINS NUMBER(2,0), 
	NUMBER_OF_BREAKS NUMBER(2,0), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
  CREATE TABLE TK_CLOCK_LOCATION_EXCEPTION_T 
   (	EXCEPTION_DT DATE, 
	EXCEPTION_TYPE VARCHAR2(3), 
	EMPLID VARCHAR2(11), 
	EMPL_RCD NUMBER(38,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(38,0), 
	TASK_ID VARCHAR2(7), 
	CLOCK_TS DATE, 
	CLOCK_ACTION_CD VARCHAR2(2), 
	IP_ADDRESS VARCHAR2(15), 
	WORK_AREA_ID NUMBER(10,0)
   ) ;
  CREATE TABLE TK_CLOCK_LOCATION_RL_T 
   (	DEPTID VARCHAR2(7), 
	WORK_AREA_ID NUMBER(10,0), 
	EMPLID VARCHAR2(10), 
	EMPL_RCD NUMBER(3,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	IP_ADDRESS VARCHAR2(15), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
  CREATE TABLE TK_CLOCK_LOG_T 
   (	EMPLID VARCHAR2(10), 
	EMPL_RCD NUMBER(3,0), 
	WORK_AREA_ID NUMBER(10,0), 
	TASK_ID NUMBER(10,0), 
	CLOCK_TS DATE, 
	CLOCK_ACTION_CD VARCHAR2(2), 
	IP_ADDRESS VARCHAR2(15), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE, 
	CLOCK_TS_TZ VARCHAR2(3)
   ) ;
  CREATE TABLE TK_DAILY_OVERTIME_RL_T 
   (	LOCATION VARCHAR2(2), 
	SAL_ADMIN_PLAN VARCHAR2(4), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE, 
	DEPTID VARCHAR2(7), 
	WORK_AREA_ID NUMBER(10,0), 
	TASK_ID NUMBER(10,0), 
	MAX_GAP NUMBER(3,0), 
	SHIFT_HOURS NUMBER(2,0), 
	OVERTIME_PREFERENCE VARCHAR2(3)
   ) ;
  CREATE TABLE TK_DEPT_LUNCH_RL_T 
   (	DEPTID VARCHAR2(7), 
	WORK_AREA_ID NUMBER(10,0), 
	EMPLID VARCHAR2(10), 
	EMPL_RCD NUMBER(3,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	REQUIRED_CLOCK_FL VARCHAR2(1), 
	MAX_MINS NUMBER(2,0), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
  CREATE TABLE TK_DOCUMENT_HEADER_SNAP_T 
   (	DOCUMENT_ID VARCHAR2(14), 
	EMPLID VARCHAR2(10), 
	PAY_END_DT DATE, 
	DOCUMENT_STATUS VARCHAR2(1), 
	SNAP_DT DATE
   ) ;
  CREATE TABLE TK_DOCUMENT_HEADER_T 
   (	DOCUMENT_ID VARCHAR2(14), 
	EMPLID VARCHAR2(10), 
	PAY_END_DT DATE, 
	DOCUMENT_STATUS VARCHAR2(1)
   ) ;
  CREATE TABLE TK_DOCUMENT_LOCK_T 
   (	DOCUMENT_ID VARCHAR2(14), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
  CREATE TABLE TK_EXPECTED_HRS_EXCEPTION_T 
   (	EXCEPTION_DT DATE, 
	EXCEPTION_TYPE VARCHAR2(3), 
	EMPLID VARCHAR2(11), 
	EMPL_RCD NUMBER(38,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(38,0), 
	TASK_ID VARCHAR2(7), 
	ACTUAL_HOURS NUMBER(3,0), 
	RULE_HOURS NUMBER(3,0), 
	WORK_AREA_ID NUMBER(10,0)
   ) ;
  CREATE TABLE TK_EXTRACT_SCHEDULE_T 
   (	PAY_END_DT DATE, 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	EXTRACT_STATUS VARCHAR2(1), 
	SCHD_EXTRACT_BEGIN_TS DATE, 
	ACTUAL_EXTRACT_BEGIN_TS DATE, 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
  CREATE TABLE TK_GRACE_PERIOD_RL_T 
   (	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	GRACE_MINS NUMBER(2,0), 
	HOUR_FACTOR NUMBER(2,2), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
  CREATE TABLE TK_HELP_DETAIL_T 
   (	HELP_TYPE VARCHAR2(4), 
	RESOURCE_KEY VARCHAR2(50), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	DETAIL_TYPE VARCHAR2(4), 
	DETAIL_ORDER NUMBER(3,0), 
	TEXT VARCHAR2(1000)
   ) ;
  CREATE TABLE TK_HELP_T 
   (	HELP_TYPE VARCHAR2(4), 
	RESOURCE_KEY VARCHAR2(500), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	TEXT VARCHAR2(4000), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TK_HOLIDAY_INCENTIVE_RL_T
--------------------------------------------------------
  CREATE TABLE TK_HOLIDAY_INCENTIVE_RL_T 
   (	LOCATION VARCHAR2(2), 
	SAL_ADMIN_PLAN VARCHAR2(4), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TK_HOURLY_HRS_RL_T
--------------------------------------------------------
  CREATE TABLE TK_HOURLY_HRS_RL_T 
   (	DEPTID VARCHAR2(7), 
	WORK_AREA_ID NUMBER(10,0), 
	EMPLID VARCHAR2(10), 
	EMPL_RCD NUMBER(3,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	DAILY_MAX_HRS NUMBER(2,0), 
	DAILY_MIN_HRS NUMBER(2,0), 
	WKLY_MAX_HRS NUMBER(3,0), 
	WKLY_MIN_HRS NUMBER(3,0), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TK_INV_ASSIGNMENT_EXCEPTION_T
--------------------------------------------------------
  CREATE TABLE TK_INV_ASSIGNMENT_EXCEPTION_T 
   (	EXCEPTION_DT DATE, 
	EXCEPTION_TYPE VARCHAR2(3), 
	EMPLID VARCHAR2(11), 
	EMPL_RCD NUMBER(38,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(38,0), 
	TASK_ID VARCHAR2(7), 
	BLOCK_BEGIN_TS DATE, 
	BLOCK_END_TS DATE, 
	ASSIGNMENT_END_DT DATE, 
	WORK_AREA_ID NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_IU_PYFND_INTRFC
--------------------------------------------------------
  CREATE TABLE TK_IU_PYFND_INTRFC 
   (	COMPANY VARCHAR2(3), 
	PAYGROUP VARCHAR2(3), 
	PAY_END_DT DATE, 
	EMPLID VARCHAR2(10), 
	EMPL_RCD NUMBER(3,0), 
	EARNS_BEGIN_DT DATE, 
	EARNS_END_DT DATE, 
	ERNCD VARCHAR2(3), 
	IU_FIN_COA_CD VARCHAR2(2), 
	IU_ACCOUNT_NBR VARCHAR2(7), 
	IU_SUB_ACCT_NBR VARCHAR2(5), 
	IU_FIN_OBJECT_CD VARCHAR2(4), 
	IU_FIN_SUB_OBJ_CD VARCHAR2(3), 
	IU_PROJECT_CD VARCHAR2(10), 
	IU_ORG_REF_ID VARCHAR2(8), 
	IU_HRS_FOR_PRD NUMBER(7,2), 
	IU_PYFND_INTRFC_ID VARCHAR2(16)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_IU_PYFND_INTRFC_BAK
--------------------------------------------------------
  CREATE TABLE TK_IU_PYFND_INTRFC_BAK 
   (	COMPANY VARCHAR2(3), 
	PAYGROUP VARCHAR2(3), 
	PAY_END_DT DATE, 
	EMPLID VARCHAR2(11), 
	EMPL_RCD NUMBER(38,0), 
	EARN_DT DATE, 
	ERNCD VARCHAR2(3), 
	IU_FIN_COA_CD VARCHAR2(2), 
	IU_ACCOUNT_NBR VARCHAR2(7), 
	IU_SUB_ACCT_NBR VARCHAR2(5), 
	IU_FIN_OBJECT_CD VARCHAR2(4), 
	IU_FIN_SUB_OBJ_CD VARCHAR2(3), 
	IU_PROJECT_CD VARCHAR2(10), 
	IU_ORG_REF_ID VARCHAR2(8), 
	HRS_FOR_PRD NUMBER(8,4), 
	IU_PYFND_INTRFC_ID VARCHAR2(16)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_KIOSK_T
--------------------------------------------------------
  CREATE TABLE TK_KIOSK_T 
   (	KIOSK_ID VARCHAR2(32), 
	KIOSK_DESC VARCHAR2(100), 
	PPLSFT_DEPT_ID VARCHAR2(10), 
	TK_USR_IP_ADDR VARCHAR2(48), 
	TK_LOG_SESN_ID VARCHAR2(32), 
	JRF_VER_NBR NUMBER(9,0) DEFAULT 0
   ) ;
--------------------------------------------------------
--  DDL for Table TK_LEAVE_BALANCE_EXCEPTION_T
--------------------------------------------------------
  CREATE TABLE TK_LEAVE_BALANCE_EXCEPTION_T 
   (	EXCEPTION_DT DATE, 
	EXCEPTION_TYPE VARCHAR2(3), 
	EMPLID VARCHAR2(11), 
	PLAN_TYPE VARCHAR2(2), 
	ERNCD VARCHAR2(3), 
	PAY_END_DT DATE, 
	AVAILABLE_HOURS NUMBER(3,0), 
	ACTUAL_HOURS NUMBER(3,0)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_LEAVE_HOURS_EXCEPTION_T
--------------------------------------------------------
  CREATE TABLE TK_LEAVE_HOURS_EXCEPTION_T 
   (	EXCEPTION_DT DATE, 
	EXCEPTION_TYPE VARCHAR2(3), 
	EMPLID VARCHAR2(11), 
	EMPL_RCD NUMBER(38,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(38,0), 
	TASK_ID VARCHAR2(7), 
	ERNCD VARCHAR2(3), 
	ACTUAL_HOURS NUMBER(3,0), 
	AVAILABLE_HOURS NUMBER(3,0), 
	WORK_AREA_ID NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_LUNCH_MINUTES_EXCEPTION_T
--------------------------------------------------------
  CREATE TABLE TK_LUNCH_MINUTES_EXCEPTION_T 
   (	EXCEPTION_DT DATE, 
	EXCEPTION_TYPE VARCHAR2(3), 
	EMPLID VARCHAR2(11), 
	EMPL_RCD NUMBER(38,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(38,0), 
	TASK_ID VARCHAR2(7), 
	BLOCK_BEGIN_TS DATE, 
	ACTUAL_MINUTES NUMBER(5,0), 
	RULE_MINUTES NUMBER(5,0), 
	WORK_AREA_ID NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_MISSED_CLOCK_EXCEPTION_T
--------------------------------------------------------
  CREATE TABLE TK_MISSED_CLOCK_EXCEPTION_T 
   (	EXCEPTION_DT DATE, 
	EXCEPTION_TYPE VARCHAR2(3), 
	EMPLID VARCHAR2(11), 
	EMPL_RCD NUMBER(38,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(38,0), 
	TASK_ID VARCHAR2(7), 
	CLOCK_TS DATE, 
	WORK_AREA_ID NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_PREFERENCE_T
--------------------------------------------------------
  CREATE TABLE TK_PREFERENCE_T 
   (	PREFERENCE_CODE VARCHAR2(2), 
	ROLE VARCHAR2(30), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	PREFERENCE_GROUP VARCHAR2(30), 
	DESCR VARCHAR2(50), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TK_ROLE_AUDIT_T
--------------------------------------------------------
  CREATE TABLE TK_ROLE_AUDIT_T 
   (	ROLE_AUDIT_ID NUMBER(10,0), 
	MODIFIED_BY_EMPLID VARCHAR2(10), 
	EMPLID VARCHAR2(10), 
	DEPTID VARCHAR2(7), 
	TK_TIME DATE, 
	TK_ROLE VARCHAR2(50), 
	OPERATION VARCHAR2(10), 
	LOCATION VARCHAR2(3)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_ROLE_CODE_T
--------------------------------------------------------
  CREATE TABLE TK_ROLE_CODE_T 
   (	ROLE_TYPE_CD VARCHAR2(2), 
	ROLE_CD VARCHAR2(2), 
	DESCR VARCHAR2(30)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_SHIFT_DIFFERENTIAL_RL_T
--------------------------------------------------------
  CREATE TABLE TK_SHIFT_DIFFERENTIAL_RL_T 
   (	LOCATION VARCHAR2(2), 
	SAL_ADMIN_PLAN VARCHAR2(4), 
	GRADE VARCHAR2(3), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	ERNCD VARCHAR2(3), 
	BEGIN_TS VARCHAR2(8), 
	END_TS VARCHAR2(8), 
	MIN_HRS NUMBER(2,0), 
	SUN VARCHAR2(1), 
	MON VARCHAR2(1), 
	TUE VARCHAR2(1), 
	WED VARCHAR2(1), 
	THU VARCHAR2(1), 
	FRI VARCHAR2(1), 
	SAT VARCHAR2(1), 
	MAX_GAP NUMBER(2,0), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TK_SYSTEM_LUNCH_RL_T
--------------------------------------------------------
  CREATE TABLE TK_SYSTEM_LUNCH_RL_T 
   (	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	BLOCK_HRS NUMBER(2,0), 
	MIN_MINS NUMBER(2,0), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TK_SYSTEM_ROLE_T
--------------------------------------------------------
  CREATE TABLE TK_SYSTEM_ROLE_T 
   (	EMPLID VARCHAR2(11), 
	ROLE_CD VARCHAR2(2)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_TASK_T
--------------------------------------------------------
  CREATE TABLE TK_TASK_T 
   (	WORK_AREA_ID NUMBER(10,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	TASK_ID NUMBER(10,0), 
	DESCR VARCHAR2(30), 
	ADMIN_DESCR VARCHAR2(30)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_TIME_BLOCK_HT
--------------------------------------------------------
  CREATE TABLE TK_TIME_BLOCK_HT 
   (	RECORD_ID NUMBER(22,0), 
	DOCUMENT_ID VARCHAR2(14), 
	EMPL_RCD NUMBER(3,0), 
	WORK_AREA_ID NUMBER(10,0), 
	TASK_ID NUMBER(10,0), 
	ERNCD VARCHAR2(3), 
	BEGIN_TS DATE, 
	END_TS DATE, 
	CLOCK_CREATED_FL VARCHAR2(1), 
	HOURS NUMBER(5,2), 
	OVERTIME_ERNCD VARCHAR2(3), 
	OVERTIME_HOURS NUMBER(5,2), 
	SHIFT_ERNCD VARCHAR2(3), 
	SHIFT_HOURS NUMBER(5,2), 
	PREMIUM_ERNCD VARCHAR2(3), 
	PREMIUM_HOURS NUMBER(5,2), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE, 
	ACTION_HISTORY VARCHAR2(10), 
	MODIFIED_BY_EMPLID VARCHAR2(10), 
	TIMESTAMP_ORIGINAL DATE, 
	BEGIN_TS_TZ VARCHAR2(3), 
	END_TS_TZ VARCHAR2(3), 
	TIMESTAMP_TZ VARCHAR2(3), 
	TIMESTAMP_ORIGINAL_TZ VARCHAR2(3)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_TIME_BLOCK_T
--------------------------------------------------------
  CREATE TABLE TK_TIME_BLOCK_T 
   (	DOCUMENT_ID VARCHAR2(14), 
	EMPL_RCD NUMBER(3,0), 
	WORK_AREA_ID NUMBER(10,0), 
	TASK_ID NUMBER(10,0), 
	ERNCD VARCHAR2(3), 
	BEGIN_TS DATE, 
	END_TS DATE, 
	CLOCK_CREATED_FL VARCHAR2(1), 
	HOURS NUMBER(5,2), 
	OVERTIME_ERNCD VARCHAR2(3), 
	OVERTIME_HOURS NUMBER(5,2), 
	SHIFT_ERNCD VARCHAR2(3), 
	SHIFT_HOURS NUMBER(5,2), 
	PREMIUM_ERNCD VARCHAR2(3), 
	PREMIUM_HOURS NUMBER(5,2), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE, 
	BEGIN_TS_TZ VARCHAR2(3), 
	END_TS_TZ VARCHAR2(3), 
	TIMESTAMP_TZ VARCHAR2(3)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_TIME_COLLECTION_RL_T
--------------------------------------------------------
  CREATE TABLE TK_TIME_COLLECTION_RL_T 
   (	DEPTID VARCHAR2(7), 
	WORK_AREA_ID NUMBER(10,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	CLOCK_USERS_FL VARCHAR2(1), 
	HRS_DISTRIBUTION_FL VARCHAR2(1), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TK_TRANSLATE_T
--------------------------------------------------------
  CREATE TABLE TK_TRANSLATE_T 
   (	FIELDNAME VARCHAR2(50), 
	FIELDVALUE VARCHAR2(4), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	DESCR VARCHAR2(30), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TK_USER_PREFERENCE_T
--------------------------------------------------------
  CREATE TABLE TK_USER_PREFERENCE_T 
   (	EMPLID VARCHAR2(10), 
	PREFERENCE_CODE VARCHAR2(2)
   ) ;
--------------------------------------------------------
--  DDL for Table TK_WEEKLY_OVERTIME_RL_T
--------------------------------------------------------
  CREATE TABLE TK_WEEKLY_OVERTIME_RL_T 
   (	MAX_HRS_ERN_PROGRAM VARCHAR2(3), 
	CONVERT_FROM_ERN_PROGRAM VARCHAR2(3), 
	CONVERT_TO_ERNCD VARCHAR2(3), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	STEP NUMBER(2,0), 
	MAX_HRS NUMBER(3,0), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TK_WORK_AREA_T
--------------------------------------------------------
  CREATE TABLE TK_WORK_AREA_T 
   (	WORK_AREA_ID NUMBER(10,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(3,0), 
	EFF_STATUS VARCHAR2(1), 
	DESCR VARCHAR2(30), 
	DEPTID VARCHAR2(7), 
	EMPL_TYPE VARCHAR2(1), 
	OVERTIME_PREFERENCE VARCHAR2(3), 
	ADMIN_DESCR VARCHAR2(30), 
	USER_EMPLID VARCHAR2(10), 
	TIMESTAMP DATE
   ) ;
--------------------------------------------------------
--  DDL for Table TK_WRKSTDY_OVT_EXCEPTION_T
--------------------------------------------------------
  CREATE TABLE TK_WRKSTDY_OVT_EXCEPTION_T 
   (	EXCEPTION_DT DATE, 
	EXCEPTION_TYPE VARCHAR2(3), 
	EMPLID VARCHAR2(11), 
	EMPL_RCD NUMBER(38,0), 
	EFFDT DATE, 
	EFFSEQ NUMBER(38,0), 
	TASK_ID NUMBER(10,0), 
	OVT_HOURS VARCHAR2(5), 
	WORK_AREA_ID NUMBER(10,0)
   ) ;
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T MODIFY (EXCEPTION_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T MODIFY (EXCEPTION_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T MODIFY (CLOCK_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T MODIFY (CLOCK_ACTION_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T MODIFY (IP_ADDRESS NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_EXCEPTION_T ADD CONSTRAINT TK_CLOCK_LOC_EXCEPTION_TP1 PRIMARY KEY (EXCEPTION_DT, EXCEPTION_TYPE, EMPLID, EMPL_RCD, EFFDT, EFFSEQ, TASK_ID, CLOCK_TS, WORK_AREA_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_TASK_T
--------------------------------------------------------
  ALTER TABLE TK_TASK_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_TASK_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_TASK_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_TASK_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_TASK_T MODIFY (DESCR NOT NULL ENABLE);
 
  ALTER TABLE TK_TASK_T ADD CONSTRAINT TK_TASK_TP1 PRIMARY KEY (WORK_AREA_ID, EFFDT, EFFSEQ, TASK_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_HOURLY_HRS_RL_T
--------------------------------------------------------
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (DEPTID NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (DAILY_MAX_HRS NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (DAILY_MIN_HRS NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (WKLY_MAX_HRS NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (WKLY_MIN_HRS NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_HOURLY_HRS_RL_T ADD CONSTRAINT TK_HOURLY_HRS_RL_TP1 PRIMARY KEY (DEPTID, WORK_AREA_ID, EMPLID, EMPL_RCD, EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_EXTRACT_SCHEDULE_T
--------------------------------------------------------
  ALTER TABLE TK_EXTRACT_SCHEDULE_T MODIFY (PAY_END_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_EXTRACT_SCHEDULE_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_EXTRACT_SCHEDULE_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_EXTRACT_SCHEDULE_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_EXTRACT_SCHEDULE_T MODIFY (EXTRACT_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_EXTRACT_SCHEDULE_T MODIFY (SCHD_EXTRACT_BEGIN_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_EXTRACT_SCHEDULE_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_EXTRACT_SCHEDULE_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_EXTRACT_SCHEDULE_T ADD CONSTRAINT TK_EXTRACT_SCHEDULE_TP1 PRIMARY KEY (PAY_END_DT, EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_EXPECTED_HRS_EXCEPTION_T
--------------------------------------------------------
  ALTER TABLE TK_EXPECTED_HRS_EXCEPTION_T MODIFY (EXCEPTION_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_EXPECTED_HRS_EXCEPTION_T MODIFY (EXCEPTION_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_EXPECTED_HRS_EXCEPTION_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_EXPECTED_HRS_EXCEPTION_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_EXPECTED_HRS_EXCEPTION_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_EXPECTED_HRS_EXCEPTION_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_EXPECTED_HRS_EXCEPTION_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_EXPECTED_HRS_EXCEPTION_T MODIFY (ACTUAL_HOURS NOT NULL ENABLE);
 
  ALTER TABLE TK_EXPECTED_HRS_EXCEPTION_T MODIFY (RULE_HOURS NOT NULL ENABLE);
 
  ALTER TABLE TK_EXPECTED_HRS_EXCEPTION_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_EXPECTED_HRS_EXCEPTION_T ADD CONSTRAINT TK_EXPECTED_HRS_EXCEPTION_TP1 PRIMARY KEY (EXCEPTION_DT, EXCEPTION_TYPE, EMPLID, EMPL_RCD, EFFDT, EFFSEQ, TASK_ID, WORK_AREA_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_HOLIDAY_INCENTIVE_RL_T
--------------------------------------------------------
  ALTER TABLE TK_HOLIDAY_INCENTIVE_RL_T MODIFY (LOCATION NOT NULL ENABLE);
 
  ALTER TABLE TK_HOLIDAY_INCENTIVE_RL_T MODIFY (SAL_ADMIN_PLAN NOT NULL ENABLE);
 
  ALTER TABLE TK_HOLIDAY_INCENTIVE_RL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_HOLIDAY_INCENTIVE_RL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_HOLIDAY_INCENTIVE_RL_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_HOLIDAY_INCENTIVE_RL_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_HOLIDAY_INCENTIVE_RL_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_HOLIDAY_INCENTIVE_RL_T ADD CONSTRAINT TK_HOLIDAY_INCENTIVE_RL_TP1 PRIMARY KEY (LOCATION, SAL_ADMIN_PLAN, EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_ROLE_CODE_T
--------------------------------------------------------
  ALTER TABLE TK_ROLE_CODE_T MODIFY (ROLE_TYPE_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_ROLE_CODE_T MODIFY (ROLE_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_ROLE_CODE_T ADD CONSTRAINT TK_ROLE_CODE_TP1 PRIMARY KEY (ROLE_TYPE_CD, ROLE_CD) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_TIME_BLOCK_T
--------------------------------------------------------
  ALTER TABLE TK_TIME_BLOCK_T MODIFY (DOCUMENT_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_T MODIFY (ERNCD NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_T MODIFY (BEGIN_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_T MODIFY (END_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_T MODIFY (CLOCK_CREATED_FL NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_T ADD CONSTRAINT TK_TIME_BLOCK_TP1 PRIMARY KEY (DOCUMENT_ID, EMPL_RCD, WORK_AREA_ID, TASK_ID, ERNCD, BEGIN_TS, END_TS, TIMESTAMP) ENABLE;
 
  ALTER TABLE TK_TIME_BLOCK_T ADD CONSTRAINT TK_TIME_BLOCK_TU1 UNIQUE (DOCUMENT_ID, EMPL_RCD, WORK_AREA_ID, TASK_ID, ERNCD, BEGIN_TS, END_TS, CLOCK_CREATED_FL) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_BREAK_EXCEPTION_T
--------------------------------------------------------
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (EXCEPTION_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (EXCEPTION_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (BLOCK_BEGIN_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (ACTUAL_MINUTES NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (RULE_MINUTES NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (ACTUAL_NUMBER_OF_BREAKS NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (RULE_NUMBER_OF_BREAKS NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_EXCEPTION_T ADD CONSTRAINT TK_BREAK_EXCEPTION_TP1 PRIMARY KEY (EXCEPTION_DT, EXCEPTION_TYPE, EMPLID, EMPL_RCD, EFFDT, EFFSEQ, TASK_ID, BLOCK_BEGIN_TS, WORK_AREA_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_LUNCH_MINUTES_EXCEPTION_T
--------------------------------------------------------
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T MODIFY (EXCEPTION_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T MODIFY (EXCEPTION_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T MODIFY (BLOCK_BEGIN_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T MODIFY (ACTUAL_MINUTES NOT NULL ENABLE);
 
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T MODIFY (RULE_MINUTES NOT NULL ENABLE);
 
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_LUNCH_MINUTES_EXCEPTION_T ADD CONSTRAINT TK_LUNCH_MINUTES_EXCEPTION_TP1 PRIMARY KEY (EXCEPTION_DT, EXCEPTION_TYPE, EMPLID, EMPL_RCD, EFFDT, EFFSEQ, TASK_ID, BLOCK_BEGIN_TS, WORK_AREA_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_KIOSK_T
--------------------------------------------------------
  ALTER TABLE TK_KIOSK_T MODIFY (KIOSK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_KIOSK_T ADD CONSTRAINT TK_KIOSK_TP1 PRIMARY KEY (KIOSK_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_CLOCK_LOG_T
--------------------------------------------------------
  ALTER TABLE TK_CLOCK_LOG_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOG_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOG_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOG_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOG_T MODIFY (CLOCK_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOG_T MODIFY (CLOCK_ACTION_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOG_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOG_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOG_T ADD CONSTRAINT TK_CLOCK_LOG_TP1 PRIMARY KEY (EMPLID, EMPL_RCD, WORK_AREA_ID, TASK_ID, CLOCK_TS, CLOCK_ACTION_CD, TIMESTAMP) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_DOCUMENT_HEADER_SNAP_T
--------------------------------------------------------
  ALTER TABLE TK_DOCUMENT_HEADER_SNAP_T MODIFY (DOCUMENT_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_HEADER_SNAP_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_HEADER_SNAP_T MODIFY (PAY_END_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_HEADER_SNAP_T MODIFY (DOCUMENT_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_HEADER_SNAP_T MODIFY (SNAP_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_HEADER_SNAP_T ADD CONSTRAINT TK_DOCUMENT_HEADER_SNAP_TP1 PRIMARY KEY (DOCUMENT_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_IU_PYFND_INTRFC
--------------------------------------------------------
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (COMPANY NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (PAYGROUP NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (PAY_END_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (EARNS_BEGIN_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (EARNS_END_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (ERNCD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (IU_FIN_COA_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (IU_ACCOUNT_NBR NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (IU_SUB_ACCT_NBR NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (IU_FIN_OBJECT_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (IU_FIN_SUB_OBJ_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (IU_PROJECT_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (IU_ORG_REF_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (IU_HRS_FOR_PRD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC MODIFY (IU_PYFND_INTRFC_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC ADD CONSTRAINT TK_IU_PYFND_INTRFCP1 PRIMARY KEY (COMPANY, PAYGROUP, PAY_END_DT, EMPLID, EMPL_RCD, EARNS_BEGIN_DT, EARNS_END_DT, ERNCD, IU_FIN_COA_CD, IU_ACCOUNT_NBR, IU_SUB_ACCT_NBR, IU_FIN_OBJECT_CD, IU_FIN_SUB_OBJ_CD, IU_PROJECT_CD, IU_ORG_REF_ID, IU_PYFND_INTRFC_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_INV_ASSIGNMENT_EXCEPTION_T
--------------------------------------------------------
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T MODIFY (EXCEPTION_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T MODIFY (EXCEPTION_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T MODIFY (BLOCK_BEGIN_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T MODIFY (BLOCK_END_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T MODIFY (ASSIGNMENT_END_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_INV_ASSIGNMENT_EXCEPTION_T ADD CONSTRAINT TK_INV_ASGNMT_EXCEPTION_TP1 PRIMARY KEY (EXCEPTION_DT, EXCEPTION_TYPE, EMPLID, EMPL_RCD, EFFDT, EFFSEQ, TASK_ID, BLOCK_BEGIN_TS, WORK_AREA_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_HELP_T
--------------------------------------------------------
  ALTER TABLE TK_HELP_T MODIFY (HELP_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_T MODIFY (RESOURCE_KEY NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_T MODIFY (TEXT NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_T ADD CONSTRAINT TK_HELP_TP1 PRIMARY KEY (HELP_TYPE, RESOURCE_KEY, EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_WORK_AREA_T
--------------------------------------------------------
  ALTER TABLE TK_WORK_AREA_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_WORK_AREA_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_WORK_AREA_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_WORK_AREA_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_WORK_AREA_T MODIFY (DESCR NOT NULL ENABLE);
 
  ALTER TABLE TK_WORK_AREA_T MODIFY (DEPTID NOT NULL ENABLE);
 
  ALTER TABLE TK_WORK_AREA_T MODIFY (EMPL_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_WORK_AREA_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_WORK_AREA_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_WORK_AREA_T ADD CONSTRAINT TK_WORK_AREA_TP1 PRIMARY KEY (WORK_AREA_ID, EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_IU_PYFND_INTRFC_BAK
--------------------------------------------------------
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (COMPANY NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (PAYGROUP NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (ERNCD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (IU_FIN_COA_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (IU_ACCOUNT_NBR NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (IU_SUB_ACCT_NBR NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (IU_FIN_OBJECT_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (IU_FIN_SUB_OBJ_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (IU_PROJECT_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (IU_ORG_REF_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (HRS_FOR_PRD NOT NULL ENABLE);
 
  ALTER TABLE TK_IU_PYFND_INTRFC_BAK MODIFY (IU_PYFND_INTRFC_ID NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TK_TIME_BLOCK_HT
--------------------------------------------------------
  ALTER TABLE TK_TIME_BLOCK_HT MODIFY (RECORD_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_HT MODIFY (DOCUMENT_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_HT MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_HT MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_HT MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_HT MODIFY (ERNCD NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_HT MODIFY (BEGIN_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_HT MODIFY (END_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_HT MODIFY (CLOCK_CREATED_FL NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_HT MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_HT MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_BLOCK_HT ADD CONSTRAINT TK_TIME_BLOCK_HTP1 PRIMARY KEY (RECORD_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_DAILY_OVERTIME_RL_T
--------------------------------------------------------
  ALTER TABLE TK_DAILY_OVERTIME_RL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_DAILY_OVERTIME_RL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_DAILY_OVERTIME_RL_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_DAILY_OVERTIME_RL_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_DAILY_OVERTIME_RL_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_DAILY_OVERTIME_RL_T MODIFY (DEPTID NOT NULL ENABLE);
 
  ALTER TABLE TK_DAILY_OVERTIME_RL_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_DAILY_OVERTIME_RL_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_DAILY_OVERTIME_RL_T ADD CONSTRAINT TK_DAILY_OVERTIME_RL_TP1 PRIMARY KEY (EFFDT, EFFSEQ, DEPTID, WORK_AREA_ID, TASK_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_WRKSTDY_OVT_EXCEPTION_T
--------------------------------------------------------
  ALTER TABLE TK_WRKSTDY_OVT_EXCEPTION_T MODIFY (EXCEPTION_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_WRKSTDY_OVT_EXCEPTION_T MODIFY (EXCEPTION_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_WRKSTDY_OVT_EXCEPTION_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_WRKSTDY_OVT_EXCEPTION_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_WRKSTDY_OVT_EXCEPTION_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_WRKSTDY_OVT_EXCEPTION_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_WRKSTDY_OVT_EXCEPTION_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_WRKSTDY_OVT_EXCEPTION_T MODIFY (OVT_HOURS NOT NULL ENABLE);
 
  ALTER TABLE TK_WRKSTDY_OVT_EXCEPTION_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_WRKSTDY_OVT_EXCEPTION_T ADD CONSTRAINT TK_WRKSTDY_OVT_EXCEPTION_TP1 PRIMARY KEY (EXCEPTION_DT, EXCEPTION_TYPE, EMPLID, EMPL_RCD, EFFDT, EFFSEQ, TASK_ID, WORK_AREA_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_PREFERENCE_T
--------------------------------------------------------
  ALTER TABLE TK_PREFERENCE_T MODIFY (PREFERENCE_CODE NOT NULL ENABLE);
 
  ALTER TABLE TK_PREFERENCE_T MODIFY (ROLE NOT NULL ENABLE);
 
  ALTER TABLE TK_PREFERENCE_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_PREFERENCE_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_PREFERENCE_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_PREFERENCE_T MODIFY (PREFERENCE_GROUP NOT NULL ENABLE);
 
  ALTER TABLE TK_PREFERENCE_T MODIFY (DESCR NOT NULL ENABLE);
 
  ALTER TABLE TK_PREFERENCE_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_PREFERENCE_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_PREFERENCE_T ADD CONSTRAINT SYS_C0074844 PRIMARY KEY (PREFERENCE_CODE, ROLE, EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_LEAVE_HOURS_EXCEPTION_T
--------------------------------------------------------
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T MODIFY (EXCEPTION_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T MODIFY (EXCEPTION_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T MODIFY (ERNCD NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T MODIFY (ACTUAL_HOURS NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T MODIFY (AVAILABLE_HOURS NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_HOURS_EXCEPTION_T ADD CONSTRAINT TK_LEAVE_HOURS_EXCEPTION_TP1 PRIMARY KEY (EXCEPTION_DT, EXCEPTION_TYPE, EMPLID, EMPL_RCD, EFFDT, EFFSEQ, TASK_ID, ERNCD, WORK_AREA_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_SHIFT_DIFFERENTIAL_RL_T
--------------------------------------------------------
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (LOCATION NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (SAL_ADMIN_PLAN NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (GRADE NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (ERNCD NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (BEGIN_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (END_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (MIN_HRS NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (SUN NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (MON NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (TUE NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (WED NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (THU NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (FRI NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (SAT NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (MAX_GAP NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_SHIFT_DIFFERENTIAL_RL_T ADD CONSTRAINT TK_SHIFT_DIFFERENTIAL_RL_TP2 PRIMARY KEY (LOCATION, SAL_ADMIN_PLAN, GRADE, EFFDT, EFFSEQ, ERNCD) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_DEPT_LUNCH_RL_T
--------------------------------------------------------
  ALTER TABLE TK_DEPT_LUNCH_RL_T MODIFY (DEPTID NOT NULL ENABLE);
 
  ALTER TABLE TK_DEPT_LUNCH_RL_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_DEPT_LUNCH_RL_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_DEPT_LUNCH_RL_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_DEPT_LUNCH_RL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_DEPT_LUNCH_RL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_DEPT_LUNCH_RL_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_DEPT_LUNCH_RL_T MODIFY (REQUIRED_CLOCK_FL NOT NULL ENABLE);
 
  ALTER TABLE TK_DEPT_LUNCH_RL_T MODIFY (MAX_MINS NOT NULL ENABLE);
 
  ALTER TABLE TK_DEPT_LUNCH_RL_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_DEPT_LUNCH_RL_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_DEPT_LUNCH_RL_T ADD CONSTRAINT TK_DEPT_LUNCH_RL_TP1 PRIMARY KEY (DEPTID, WORK_AREA_ID, EMPLID, EMPL_RCD, EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_USER_PREFERENCE_T
--------------------------------------------------------
  ALTER TABLE TK_USER_PREFERENCE_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_USER_PREFERENCE_T MODIFY (PREFERENCE_CODE NOT NULL ENABLE);
 
  ALTER TABLE TK_USER_PREFERENCE_T ADD CONSTRAINT TK_USER_PREFERENCE_TP1 PRIMARY KEY (EMPLID, PREFERENCE_CODE) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_TIME_COLLECTION_RL_T
--------------------------------------------------------
  ALTER TABLE TK_TIME_COLLECTION_RL_T MODIFY (DEPTID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_COLLECTION_RL_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_COLLECTION_RL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_COLLECTION_RL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_COLLECTION_RL_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_COLLECTION_RL_T MODIFY (CLOCK_USERS_FL NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_COLLECTION_RL_T MODIFY (HRS_DISTRIBUTION_FL NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_COLLECTION_RL_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_COLLECTION_RL_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_TIME_COLLECTION_RL_T ADD CONSTRAINT TK_TIME_COLLECTION_RL_TP1 PRIMARY KEY (DEPTID, WORK_AREA_ID, EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_DOCUMENT_LOCK_T
--------------------------------------------------------
  ALTER TABLE TK_DOCUMENT_LOCK_T MODIFY (DOCUMENT_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_LOCK_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_LOCK_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_LOCK_T ADD CONSTRAINT TK_DOCUMENT_LOCK_TP1 PRIMARY KEY (DOCUMENT_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_CLOCK_LOCATION_RL_T
--------------------------------------------------------
  ALTER TABLE TK_CLOCK_LOCATION_RL_T MODIFY (DEPTID NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_RL_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_RL_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_RL_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_RL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_RL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_RL_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_RL_T MODIFY (IP_ADDRESS NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_RL_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_RL_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_CLOCK_LOCATION_RL_T ADD CONSTRAINT TK_CLOCK_LOCATION_RL_TP1 PRIMARY KEY (DEPTID, WORK_AREA_ID, EMPLID, EMPL_RCD, EFFDT, EFFSEQ, IP_ADDRESS) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_DOCUMENT_HEADER_T
--------------------------------------------------------
  ALTER TABLE TK_DOCUMENT_HEADER_T MODIFY (DOCUMENT_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_HEADER_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_HEADER_T MODIFY (PAY_END_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_HEADER_T MODIFY (DOCUMENT_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_DOCUMENT_HEADER_T ADD CONSTRAINT TK_DOCUMENT_HEADER_TP1 PRIMARY KEY (DOCUMENT_ID) ENABLE;
 
  ALTER TABLE TK_DOCUMENT_HEADER_T ADD CONSTRAINT TK_DOCUMENT_HEADER_TU1 UNIQUE (EMPLID, PAY_END_DT) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_LEAVE_BALANCE_EXCEPTION_T
--------------------------------------------------------
  ALTER TABLE TK_LEAVE_BALANCE_EXCEPTION_T MODIFY (EXCEPTION_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_BALANCE_EXCEPTION_T MODIFY (EXCEPTION_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_BALANCE_EXCEPTION_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_BALANCE_EXCEPTION_T MODIFY (PLAN_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_BALANCE_EXCEPTION_T MODIFY (ERNCD NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_BALANCE_EXCEPTION_T MODIFY (PAY_END_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_BALANCE_EXCEPTION_T MODIFY (AVAILABLE_HOURS NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_BALANCE_EXCEPTION_T MODIFY (ACTUAL_HOURS NOT NULL ENABLE);
 
  ALTER TABLE TK_LEAVE_BALANCE_EXCEPTION_T ADD CONSTRAINT TK_LEAVE_BALANCE_EXCEPTION_TP1 PRIMARY KEY (EXCEPTION_DT, EXCEPTION_TYPE, EMPLID, PLAN_TYPE, ERNCD) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_MISSED_CLOCK_EXCEPTION_T
--------------------------------------------------------
  ALTER TABLE TK_MISSED_CLOCK_EXCEPTION_T MODIFY (EXCEPTION_DT NOT NULL ENABLE);
 
  ALTER TABLE TK_MISSED_CLOCK_EXCEPTION_T MODIFY (EXCEPTION_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_MISSED_CLOCK_EXCEPTION_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_MISSED_CLOCK_EXCEPTION_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_MISSED_CLOCK_EXCEPTION_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_MISSED_CLOCK_EXCEPTION_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_MISSED_CLOCK_EXCEPTION_T MODIFY (TASK_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_MISSED_CLOCK_EXCEPTION_T MODIFY (CLOCK_TS NOT NULL ENABLE);
 
  ALTER TABLE TK_MISSED_CLOCK_EXCEPTION_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_MISSED_CLOCK_EXCEPTION_T ADD CONSTRAINT TK_MISSED_CLOCK_EXCEPTION_TP1 PRIMARY KEY (EXCEPTION_DT, EXCEPTION_TYPE, EMPLID, EMPL_RCD, EFFDT, EFFSEQ, TASK_ID, WORK_AREA_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_HELP_DETAIL_T
--------------------------------------------------------
  ALTER TABLE TK_HELP_DETAIL_T MODIFY (HELP_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_DETAIL_T MODIFY (RESOURCE_KEY NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_DETAIL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_DETAIL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_DETAIL_T MODIFY (DETAIL_TYPE NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_DETAIL_T MODIFY (DETAIL_ORDER NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_DETAIL_T MODIFY (TEXT NOT NULL ENABLE);
 
  ALTER TABLE TK_HELP_DETAIL_T ADD CONSTRAINT TK_HELP_DETAIL_TP1 PRIMARY KEY (HELP_TYPE, RESOURCE_KEY, EFFDT, EFFSEQ, DETAIL_TYPE, DETAIL_ORDER) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_SYSTEM_LUNCH_RL_T
--------------------------------------------------------
  ALTER TABLE TK_SYSTEM_LUNCH_RL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_SYSTEM_LUNCH_RL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_SYSTEM_LUNCH_RL_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_SYSTEM_LUNCH_RL_T MODIFY (BLOCK_HRS NOT NULL ENABLE);
 
  ALTER TABLE TK_SYSTEM_LUNCH_RL_T MODIFY (MIN_MINS NOT NULL ENABLE);
 
  ALTER TABLE TK_SYSTEM_LUNCH_RL_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_SYSTEM_LUNCH_RL_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_SYSTEM_LUNCH_RL_T ADD CONSTRAINT TK_SYSTEM_LUNCH_RL_TP1 PRIMARY KEY (EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_TRANSLATE_T
--------------------------------------------------------
  ALTER TABLE TK_TRANSLATE_T MODIFY (FIELDNAME NOT NULL ENABLE);
 
  ALTER TABLE TK_TRANSLATE_T MODIFY (FIELDVALUE NOT NULL ENABLE);
 
  ALTER TABLE TK_TRANSLATE_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_TRANSLATE_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_TRANSLATE_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_TRANSLATE_T MODIFY (DESCR NOT NULL ENABLE);
 
  ALTER TABLE TK_TRANSLATE_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_TRANSLATE_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_TRANSLATE_T ADD CONSTRAINT TK_TRANSLATE_TP1 PRIMARY KEY (FIELDNAME, FIELDVALUE, EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_BATCH_MESSAGE_T
--------------------------------------------------------
  ALTER TABLE TK_BATCH_MESSAGE_T MODIFY (MESSAGE_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_BATCH_MESSAGE_T MODIFY (PROCESS_NAME NOT NULL ENABLE);
 
  ALTER TABLE TK_BATCH_MESSAGE_T MODIFY (PROCESS_DATE NOT NULL ENABLE);
 
  ALTER TABLE TK_BATCH_MESSAGE_T MODIFY (MESSAGE NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TK_ROLE_AUDIT_T
--------------------------------------------------------
  ALTER TABLE TK_ROLE_AUDIT_T MODIFY (ROLE_AUDIT_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_ROLE_AUDIT_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_ROLE_AUDIT_T MODIFY (TK_TIME NOT NULL ENABLE);
 
  ALTER TABLE TK_ROLE_AUDIT_T MODIFY (TK_ROLE NOT NULL ENABLE);
 
  ALTER TABLE TK_ROLE_AUDIT_T MODIFY (OPERATION NOT NULL ENABLE);
 
  ALTER TABLE TK_ROLE_AUDIT_T ADD CONSTRAINT TK_ROLE_AUDIT_TP1 PRIMARY KEY (ROLE_AUDIT_ID) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_GRACE_PERIOD_RL_T
--------------------------------------------------------
  ALTER TABLE TK_GRACE_PERIOD_RL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_GRACE_PERIOD_RL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_GRACE_PERIOD_RL_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_GRACE_PERIOD_RL_T MODIFY (GRACE_MINS NOT NULL ENABLE);
 
  ALTER TABLE TK_GRACE_PERIOD_RL_T MODIFY (HOUR_FACTOR NOT NULL ENABLE);
 
  ALTER TABLE TK_GRACE_PERIOD_RL_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_GRACE_PERIOD_RL_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_GRACE_PERIOD_RL_T ADD CONSTRAINT TK_GRACE_PERIOD_RL_TP1 PRIMARY KEY (EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_WEEKLY_OVERTIME_RL_T
--------------------------------------------------------
  ALTER TABLE TK_WEEKLY_OVERTIME_RL_T MODIFY (MAX_HRS_ERN_PROGRAM NOT NULL ENABLE);
 
  ALTER TABLE TK_WEEKLY_OVERTIME_RL_T MODIFY (CONVERT_FROM_ERN_PROGRAM NOT NULL ENABLE);
 
  ALTER TABLE TK_WEEKLY_OVERTIME_RL_T MODIFY (CONVERT_TO_ERNCD NOT NULL ENABLE);
 
  ALTER TABLE TK_WEEKLY_OVERTIME_RL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_WEEKLY_OVERTIME_RL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_WEEKLY_OVERTIME_RL_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_WEEKLY_OVERTIME_RL_T MODIFY (STEP NOT NULL ENABLE);
 
  ALTER TABLE TK_WEEKLY_OVERTIME_RL_T MODIFY (MAX_HRS NOT NULL ENABLE);
 
  ALTER TABLE TK_WEEKLY_OVERTIME_RL_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_WEEKLY_OVERTIME_RL_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_WEEKLY_OVERTIME_RL_T ADD CONSTRAINT TK_WEEKLY_OVERTIME_RL_TP1 PRIMARY KEY (MAX_HRS_ERN_PROGRAM, CONVERT_FROM_ERN_PROGRAM, CONVERT_TO_ERNCD, EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_SYSTEM_ROLE_T
--------------------------------------------------------
  ALTER TABLE TK_SYSTEM_ROLE_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_SYSTEM_ROLE_T MODIFY (ROLE_CD NOT NULL ENABLE);
 
  ALTER TABLE TK_SYSTEM_ROLE_T ADD CONSTRAINT TK_SYSTEM_ROLE_TP1 PRIMARY KEY (EMPLID, ROLE_CD) ENABLE;
--------------------------------------------------------
--  Constraints for Table TK_BREAK_RL_T
--------------------------------------------------------
  ALTER TABLE TK_BREAK_RL_T MODIFY (DEPTID NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T MODIFY (WORK_AREA_ID NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T MODIFY (EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T MODIFY (EMPL_RCD NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T MODIFY (EFFDT NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T MODIFY (EFFSEQ NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T MODIFY (EFF_STATUS NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T MODIFY (BLOCK_HRS NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T MODIFY (MAX_MINS NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T MODIFY (NUMBER_OF_BREAKS NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T MODIFY (USER_EMPLID NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T MODIFY (TIMESTAMP NOT NULL ENABLE);
 
  ALTER TABLE TK_BREAK_RL_T ADD CONSTRAINT TK_BREAK_RL_TP1 PRIMARY KEY (DEPTID, WORK_AREA_ID, EMPLID, EMPL_RCD, EFFDT, EFFSEQ) ENABLE;
--------------------------------------------------------
--  DDL for Index TK_BATCH_MESSAGE_TP1
--------------------------------------------------------
  CREATE UNIQUE INDEX TK_BATCH_MESSAGE_TP1 ON TK_BATCH_MESSAGE_T (MESSAGE_ID) 
  ;
  CREATE INDEX TK_DOCUMENT_HEADERP1 ON TK_DOCUMENT_HEADER_T (PAY_END_DT, EMPLID) 
  ;
  CREATE INDEX FP_DOC_TYPE_TI2 ON FP_DOC_TYPE_T (FDOC_GRP_CD) 
  ;
--------------------------------------------------------
--  DDL for View TK_DAILY_NOTIFICATION_V
--------------------------------------------------------
  CREATE OR REPLACE VIEW TK_DAILY_NOTIFICATION_V (DOCUMENT_ID, EMPLID, MODIFIED_BY_EMPLID, PAY_END_DT, TIMESTAMP) AS 
  SELECT h.DOCUMENT_ID, h.EMPLID, tb.MODIFIED_BY_EMPLID, h.PAY_END_DT, to_date(TO_CHAR(TIMESTAMP, 'MM-DD-YYYY'),'MM-DD-YYYY') timestamp FROM
  TK.TK_TIME_BLOCK_HT tb, tk.TK_DOCUMENT_HEADER_T h
WHERE
tb.DOCUMENT_ID = h.DOCUMENT_ID
AND tb.MODIFIED_BY_EMPLID != h.EMPLID
AND MODIFIED_BY_EMPLID != 'tk-user'
GROUP BY h.DOCUMENT_ID, h.EMPLID, tb.MODIFIED_BY_EMPLID, h.PAY_END_DT, to_date(TO_CHAR(TIMESTAMP, 'MM-DD-YYYY'),'MM-DD-YYYY')
ORDER BY h.DOCUMENT_ID;

--CREATE table TK_PAYROLL_EXT_STATUS(
-- total_docs NUMBER(10,0) not NULL,
-- proc_docs_amt NUMBER(10,0) not NULL
--);

create sequence payroll_ext_cur minvalue 0 start with 1 increment by 1;

insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Clocked Out','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'CLOCK_ACTION_CD','CO',to_timestamp('23-OCT-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Clocked in','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'CLOCK_ACTION_CD','CI',to_timestamp('23-OCT-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Out for lunch','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'CLOCK_ACTION_CD','LO',to_timestamp('23-OCT-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Back from lunch','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'CLOCK_ACTION_CD','LI',to_timestamp('23-OCT-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Out for break','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'CLOCK_ACTION_CD','BO',to_timestamp('23-OCT-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Back from break','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'CLOCK_ACTION_CD','BI',to_timestamp('23-OCT-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Complete','A',to_timestamp('24-NOV-05','DD-MON-RR HH.MI.SSXFF AM'),0,'EXTRACT_STATUS','C',to_timestamp('12-DEC-08','DD-MON-RR HH.MI.SSXFF AM'),'0001433321');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('In-Progress','A',to_timestamp('24-NOV-08','DD-MON-RR HH.MI.SSXFF AM'),0,'EXTRACT_STATUS','I',to_timestamp('12-DEC-08','DD-MON-RR HH.MI.SSXFF AM'),'0001433321');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Complete','A',to_timestamp('01-DEC-05','DD-MON-RR HH.MI.SSXFF AM'),0,'EXTRACT_STATUS','C',to_timestamp('12-DEC-08','DD-MON-RR HH.MI.SSXFF AM'),'0001433321');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Approaching Maximum Daily Hrs','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','AMD',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Approaching Maximum Weekly','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','AMW',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Approaching Weekly Overtime','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','AWO',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Below Expected Hours','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','BEH',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Below Minimum Lunch TIME','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','BLT',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Below Minimum Daily Hours','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','BMD',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Below Minimum Weekly','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','BMW',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Exceeded Break Segments','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','EBS',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Exceeded Break TIME','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','EBT',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Exceeded Expected Hours','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','EEH',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Exceeded Leave Balances','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','ELB',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Exceeded Maximum Lunch TIME','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','ELT',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Exceeded Maximum Daily Hours','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','EMD',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Exceeded Minimum Weekly','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','EMW',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Hours on Invalid Assignment','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','HIA',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Missed Clock OUT','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','MCO',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Unexpected Clock Location','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','UCL',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Workstudy Overtime Usage','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','WSO',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Hours on Pending Assignment','A',to_timestamp('01-JAN-80','DD-MON-RR HH.MI.SSXFF AM'),0,'EXCEPTION_TYPE','HPA',to_timestamp('05-JUL-06','DD-MON-RR HH.MI.SSXFF AM'),'System');
insert into TK_TRANSLATE_T (DESCR,EFF_STATUS,EFFDT,EFFSEQ,FIELDNAME,FIELDVALUE,TIMESTAMP,USER_EMPLID) values ('Pending','A',to_timestamp('24-NOV-10','DD-MON-RR HH.MI.SSXFF AM'),0,'EXTRACT_STATUS','P',to_timestamp('12-DEC-08','DD-MON-RR HH.MI.SSXFF AM'),'0001433321');

-- https://uisapp2.iu.edu/jira-prd/browse/TK-506
alter table TK.TK_CLOCK_LOCATION_RL_T add supress_warning VARCHAR2(1) ;