--
-- MySql
--
DROP TABLE IF EXISTS `EPTO_DOCUMENT_T`;
CREATE TABLE `EPTO_DOCUMENT_T` (
    DOCUMENT_ID     VARCHAR(14) NULL,
    DOCUMENT_STATUS VARCHAR(1) NULL,
	DOCUMENT_CLASS  VARCHAR(255) NULL,
    EMPLID 			VARCHAR(50) NULL,
    MONTH 			DATE NULL,
	CONSTRAINT EPTO_DOCUMENT_PK PRIMARY KEY(DOCUMENT_ID, EMPLID, MONTH)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `EPTO_CONFIG_T`;
CREATE TABLE `EPTO_CONFIG_T` (
    EPTO_CONFIG_KEY     VARCHAR(128) NOT NULL,
    EPTO_CONFIG_VALUE   VARCHAR(128) NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `EPTO_CONFIG_S`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_CONFIG_S` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

DROP TABLE IF EXISTS `EPTO_LEDGER_T`;
CREATE TABLE `EPTO_LEDGER_T` (
    LEDGER_ID               		BIGINT(19) NOT NULL,
    PTO_DATE                		DATE NOT NULL,
    EMPLID                  		VARCHAR(50) NOT NULL,
	LEAVE_CODE_PSEUDO_KEY   		DECIMAL(15,0) NULL,
    LEAVE_CODE              		VARCHAR(25) NOT NULL,
    SCHED_TIME_OFF_PSEUDO_KEY       DECIMAL(15,0) NULL,
	ACCRUAL_CATEGORY_PSEUDO_KEY 	DECIMAL(15,0) NULL,
    STATUS                  		DECIMAL(1,0) NOT NULL,
    HOURS                   		DECIMAL(8,4) NOT NULL,
    APPLY_TO_YTD_USED         		DECIMAL(1,0) NOT NULL,
    DOCUMENT_ID             		VARCHAR(14) NULL,
    EMPLID_ACTIVATED        		VARCHAR(50) NOT NULL,
    EMPLID_INACTIVATED      		VARCHAR(50) NULL,
    TIMESTAMP_ACTIVATED     		DATE NOT NULL,
    TIMESTAMP_INACTIVATED   		DATE NULL,
    ACCRUAL_GENERATED       		DECIMAL(1,0) NOT NULL,
    LOCKING_NBR             		DECIMAL(15,0) NOT NULL,
    DESCRIPTION             		VARCHAR(254) NULL,
	BLOCK_ID						BIGINT(19) NULL,
	ALT_SCHED_TIME_OFF				VARCHAR(254) NULL,
	DO_NOT_ALLOW_REMOVAL			DECIMAL(1,0) DEFAULT 0 NULL,
	MESSAGE							DECIMAL(1,0) DEFAULT 0,
	EFFDT DATE NOT NULL,
	ACTIVE_IND VARCHAR(1) NOT NULL DEFAULT '1',
	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1',
  CONSTRAINT LEDGER_PK PRIMARY KEY(LEDGER_ID)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE INDEX LEDGER_PTO_DATE_IDX ON EPTO_LEDGER_T(PTO_DATE);
CREATE INDEX LEDGER_EMPLID_IDX ON EPTO_LEDGER_T(EMPLID);
CREATE INDEX LEDGER_LEAVE_CODE_PSK_IDX ON EPTO_LEDGER_T(LEAVE_CODE_PSEUDO_KEY);
CREATE INDEX LEDGER_LEAVE_CODE_IDX ON EPTO_LEDGER_T(LEAVE_CODE);
CREATE INDEX LEDGER_SCHED_TIME_OFF_PSK_IDX ON EPTO_LEDGER_T(SCHED_TIME_OFF_PSEUDO_KEY);
CREATE INDEX LEDGER_ACCRUAL_CAT_PSK_IDX ON EPTO_LEDGER_T(ACCRUAL_CATEGORY_PSEUDO_KEY);

DROP TABLE IF EXISTS `EPTO_LEDGER_S`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_LEDGER_S` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

DROP TABLE IF EXISTS `EPTO_BLOCK_ID_S`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_BLOCK_ID_S` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

DROP TABLE IF EXISTS `EPTO_LEAVE_PLAN_T`;
CREATE TABLE `EPTO_LEAVE_PLAN_T` (
 	LEAVE_PLAN_PSEUDO_KEY  	BIGINT(19) NOT NULL,
	CAMPUS_CD           	VARCHAR(25) NOT NULL,
    PLAN_TYPE           	VARCHAR(25) NOT NULL,
    DESCRIPTION         	VARCHAR(255) NULL,
    JAVA_CLASS          	VARCHAR(255) NOT NULL,
    DOCUMENT_ID         	VARCHAR(14) NOT NULL,
    PREVIOUS_DOCUMENT_ID	VARCHAR(14) NULL,
    EFFDT DATE NOT NULL,
	ACTIVE_IND VARCHAR(1) NOT NULL DEFAULT '1',
	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1',
	CONSTRAINT LEAVE_PLAN_PK PRIMARY KEY(LEAVE_PLAN_PSEUDO_KEY, DOCUMENT_ID)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE INDEX LEAVE_PLAN_PSK_IDX ON EPTO_LEAVE_PLAN_T(LEAVE_PLAN_PSEUDO_KEY);
CREATE INDEX LEAVE_PLAN_CAMPUS_CD_IDX ON EPTO_LEAVE_PLAN_T(CAMPUS_CD);
CREATE INDEX LEAVE_PLAN_PLAN_TYPE_IDX ON EPTO_LEAVE_PLAN_T(PLAN_TYPE);
CREATE INDEX LEAVE_PLAN_DOCUMENT_ID_IDX ON EPTO_LEAVE_PLAN_T(DOCUMENT_ID);
CREATE INDEX LEAVE_PLAN_EFFECTIVE_DATE_IDX ON EPTO_LEAVE_PLAN_T(EFFDT);

DROP TABLE IF EXISTS `EPTO_LEAVE_PLAN_S`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_LEAVE_PLAN_S` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

DROP TABLE IF EXISTS `EPTO_ACCRUAL_CATEGORY_RULE_T`;
CREATE TABLE `EPTO_ACCRUAL_CATEGORY_RULE_T` (
    ACCRUAL_CATEGORY_RULE_PSK BIGINT(19) NOT NULL,
    ACCRUAL_CATEGORY_PSEUDO_KEY DECIMAL(15,0) NOT NULL,
    DOCUMENT_ID                 VARCHAR(19) NULL,
    START_MONTHS                DECIMAL(2,0) NOT NULL,
    END_MONTHS                  DECIMAL(5,0) NULL,
    ACCRUAL_RT_HOURS            DECIMAL(5,0) NULL,
    MAX_TAKEN                   DECIMAL(5,0) NULL,
    MAX_CARRY_OVER              DECIMAL(5,0) NULL,
    TRANSFER_TO_AMOUNT          DECIMAL(5,0) NULL,
    TRANSFER_FROM_AMOUNT        DECIMAL(5,0) NULL,
    EFFDT DATE NOT NULL,
	ACTIVE_IND DECIMAL(1,0) NOT NULL DEFAULT '1',
	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1',
	CONSTRAINT ACCRUAL_CATEGORY_RULE_PK PRIMARY KEY(ACCRUAL_CATEGORY_RULE_PSK)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE INDEX ACCR_CAT_RULE_ACCR_CAT_PSK_IDX ON EPTO_ACCRUAL_CATEGORY_RULE_T(ACCRUAL_CATEGORY_PSEUDO_KEY);
CREATE INDEX ACCRUAL_CAT_RULE_DOC_ID_IDX ON EPTO_ACCRUAL_CATEGORY_RULE_T(DOCUMENT_ID);

DROP TABLE IF EXISTS `EPTO_ACCRUAL_CATEGORY_RULE_S`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_ACCRUAL_CATEGORY_RULE_S` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

DROP TABLE IF EXISTS `EPTO_ACCRUAL_CATEGORY_T`;
CREATE TABLE `EPTO_ACCRUAL_CATEGORY_T` (
	ACCRUAL_CATEGORY_PSEUDO_KEY BIGINT(19) NOT NULL,
    LEAVE_PLAN_PSEUDO_KEY BIGINT(19) NOT NULL,
    ACCRUAL_CAT     VARCHAR(25) NOT NULL,
    PRORATION       DECIMAL(1,0) NULL,
    SHOW_ON_GRID    VARCHAR(1) NULL,
    DEFAULT_ACCRUAL_CAT    DECIMAL(1,0) NULL,
    DOCUMENT_ID     VARCHAR(19) NOT NULL,
    PREVIOUS_DOCUMENT_ID     VARCHAR(19) NULL,
    EFFDT DATE NOT NULL,
	ACTIVE_IND DECIMAL(1,0) NOT NULL DEFAULT '1',
	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1',
	CONSTRAINT ACCRUAL_CATEGORY_PK PRIMARY KEY(ACCRUAL_CATEGORY_PSEUDO_KEY, DOCUMENT_ID)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE INDEX ACCRUAL_CAT_PSK_IDX ON EPTO_ACCRUAL_CATEGORY_T(ACCRUAL_CATEGORY_PSEUDO_KEY);
CREATE INDEX ACCRUAL_CAT_LEAVE_PLAN_PSK_IDX ON EPTO_ACCRUAL_CATEGORY_T(LEAVE_PLAN_PSEUDO_KEY);
CREATE INDEX ACCRUAL_CAT_ACCRUAL_CAT_IDX ON EPTO_ACCRUAL_CATEGORY_T(ACCRUAL_CAT);
CREATE INDEX ACCRUAL_CAT_EFFDT_IDX ON EPTO_ACCRUAL_CATEGORY_T(EFFDT);
CREATE INDEX ACCRUAL_CAT_DOC_ID_IDX ON EPTO_ACCRUAL_CATEGORY_T(DOCUMENT_ID);

DROP TABLE IF EXISTS `EPTO_ACCRUAL_CATEGORY_S`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_ACCRUAL_CATEGORY_S` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

DROP TABLE IF EXISTS `EPTO_ROLE_T`;
CREATE TABLE `EPTO_ROLE_T` (
	ROLE_PSEUDO_KEY BIGINT(19) NOT NULL,
    SUPERVISOR_POS  VARCHAR(18) NOT NULL,
    ROLE_TARGET_POS VARCHAR(18) NOT NULL,
    ROLE            VARCHAR(25) NOT NULL,
	TARGET_EMPLID  	VARCHAR(50),
    EXPDT           DATE NULL,
    DOCUMENT_ID     VARCHAR(19) NOT NULL,
    PREVIOUS_DOCUMENT_ID	VARCHAR(14) NULL,
    EFFDT DATE NOT NULL,
    ACTIVE_IND DECIMAL(1,0) NOT NULL DEFAULT '1',
  	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID varchar(36) collate utf8_bin NOT NULL,
  	VER_NBR decimal(8,0) NOT NULL default '1',
	CONSTRAINT ROLE_PK PRIMARY KEY(ROLE_PSEUDO_KEY, DOCUMENT_ID)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE INDEX ROLE_PSK_IDX ON EPTO_ROLE_T(ROLE_PSEUDO_KEY);
CREATE INDEX ROLE_EFFDT_IDX ON EPTO_ROLE_T(EFFDT);
CREATE INDEX ROLE_PSK_DOC_ID_IDX ON EPTO_ROLE_T(DOCUMENT_ID);

DROP TABLE IF EXISTS `EPTO_ROLE_S`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_ROLE_S` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

DROP TABLE IF EXISTS `EPTO_LEAVE_CODE_T`;
CREATE TABLE `EPTO_LEAVE_CODE_T` (
    LEAVE_CODE_PSEUDO_KEY      	BIGINT(19) NOT NULL,
    ACCRUAL_CATEGORY_PSEUDO_KEY	DECIMAL(15,0) NOT NULL,
    LEAVE_CODE                 	VARCHAR(25) NOT NULL,
    DISPLAY_NAME               	VARCHAR(50) NOT NULL,
    ALLOW_SCHEDULED_DAYS       	DECIMAL(1,0) DEFAULT 0 NOT NULL,
    ACCRUAL_EARNED             	DECIMAL(1,0) DEFAULT 0 NOT NULL,
    DEFAULT_HOURS               DECIMAL(5,0) NOT NULL,
    REPORT_IN_HOURS            	DECIMAL(1,0) DEFAULT 0 NOT NULL,
    REPORT_IN_FULL_HOURS        DECIMAL(1,0) DEFAULT 0 NOT NULL,
    REPORT_IN_HALF_DAYS        	DECIMAL(1,0) DEFAULT 0 NOT NULL,
    REPORT_IN_FULL_DAYS        	DECIMAL(1,0) DEFAULT 0 NOT NULL,
    APPLY_TO_YEARLY_MAX        	DECIMAL(1,0) DEFAULT 0 NOT NULL,
    AFFECTS_HOLIDAY_ACCRUAL     DECIMAL(1,0) DEFAULT 0 NOT NULL,
    DOCUMENT_ID                	VARCHAR(14) NOT NULL,
    PREVIOUS_DOCUMENT_ID       	VARCHAR(14) NULL,
    BASIC                      	DECIMAL(1,0) DEFAULT 0 NOT NULL,
    ADVANCE                    	DECIMAL(1,0) DEFAULT 0 NOT NULL,
	VALIDATION_CLASS            VARCHAR(255),
	EFFDT DATE NOT NULL,
	ACTIVE_IND DECIMAL(1,0) NOT NULL DEFAULT '1',
	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1',
    CONSTRAINT LEAVE_CODE_PK PRIMARY KEY(LEAVE_CODE_PSEUDO_KEY, DOCUMENT_ID)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE INDEX LEAVE_CODE_PSK_IDX ON EPTO_LEAVE_CODE_T(LEAVE_CODE_PSEUDO_KEY);
CREATE INDEX LEAVE_CODE_ACCR_CAT_PSK_IDX ON EPTO_LEAVE_CODE_T(ACCRUAL_CATEGORY_PSEUDO_KEY);
CREATE INDEX LEAVE_CODE_LEAVE_CODE_IDX ON EPTO_LEAVE_CODE_T(LEAVE_CODE);
CREATE INDEX LEAVE_CODE_EFFDT_IDX ON EPTO_LEAVE_CODE_T(EFFDT);
CREATE INDEX LEAVE_CODE_DOC_ID_IDX ON EPTO_LEAVE_CODE_T(PREVIOUS_DOCUMENT_ID);

DROP TABLE IF EXISTS `EPTO_LEAVE_CODE_S`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_LEAVE_CODE_S` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

DROP TABLE IF EXISTS `EPTO_SCHEDULED_TIME_OFF_T`;
CREATE TABLE `EPTO_SCHEDULED_TIME_OFF_T` (
    SCHED_TIME_OFF_PSEUDO_KEY	BIGINT(19) NOT NULL,
    LEAVE_CODE_PSEUDO_KEY      	DECIMAL(15,0) NOT NULL,
    SCHEDULED_DATE           	DATE NULL,
    ACCRUAL_DATE             	DATE NOT NULL,
    EXPIRATION_DATE          	DATE NOT NULL,
    DESCRIPTION              	VARCHAR(25) NOT NULL,
    DOCUMENT_ID              	VARCHAR(14) NOT NULL,
    PREVIOUS_DOCUMENT_ID     	VARCHAR(14) NULL,
    EFFDT DATE NOT NULL,
    ACTIVE_IND                    	DECIMAL(1,0) DEFAULT 1 NOT NULL,

	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1',
	CONSTRAINT SCHED_TIME_OFF_PK PRIMARY KEY(SCHED_TIME_OFF_PSEUDO_KEY, DOCUMENT_ID)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE INDEX SCHED_TIME_PSK_IDX ON EPTO_SCHEDULED_TIME_OFF_T(SCHED_TIME_OFF_PSEUDO_KEY);
CREATE INDEX SCHED_TIME_LEAVE_CODE_PSK_IDX ON EPTO_SCHEDULED_TIME_OFF_T(LEAVE_CODE_PSEUDO_KEY);
CREATE INDEX SCHED_TIME_OFF_DOC_ID_IDX ON EPTO_SCHEDULED_TIME_OFF_T(DOCUMENT_ID);

DROP TABLE IF EXISTS `EPTO_SCHEDULED_TIME_OFF_S`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_SCHEDULED_TIME_OFF_S` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

DROP TABLE IF EXISTS `EPTO_EMPL_SCHEDULED_TIME_OFF_T`;
CREATE TABLE `EPTO_EMPL_SCHEDULED_TIME_OFF_T` (
    EMPL_SCHED_TIME_OFF_PSEUDO_KEY	BIGINT(19) NOT NULL,
 	SHOWN_ON_CALENDAR              	DECIMAL(1,0) DEFAULT 1 NOT NULL,
    SCHEDULED_DATE                	DATE NULL,
    ACCRUAL_DATE                  	DATE NOT NULL,
    EXPIRATION_DATE               	DATE NOT NULL,
    SCHED_TIME_OFF_PSEUDO_KEY     	DECIMAL(15,0) NOT NULL,
    DESCRIPTION                   	VARCHAR(25) NOT NULL,
    DOCUMENT_ID                   	VARCHAR(36) NULL,
    PREVIOUS_DOCUMENT_ID          	VARCHAR(36) NULL,
    EMPLID                        	VARCHAR(50) NOT NULL,
    HOURS                           DECIMAL(8,4) NOT NULL,
    EFFDT DATE NOT NULL,
    ACTIVE_IND                    	DECIMAL(1,0) DEFAULT 1 NOT NULL,
	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1',
    CONSTRAINT EMPL_SCHED_TIME_OFF_PK PRIMARY KEY(EMPL_SCHED_TIME_OFF_PSEUDO_KEY, DOCUMENT_ID)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE INDEX EMPL_SCHED_PSK_IDX ON EPTO_EMPL_SCHEDULED_TIME_OFF_T(EMPL_SCHED_TIME_OFF_PSEUDO_KEY);
CREATE INDEX EMPL_SCHED_SCHED_PSK_IDX ON EPTO_EMPL_SCHEDULED_TIME_OFF_T(SCHED_TIME_OFF_PSEUDO_KEY);
CREATE INDEX EMPL_SCHED_EMPLID_IDX ON EPTO_EMPL_SCHEDULED_TIME_OFF_T(EMPLID);
CREATE INDEX EMPL_SCHED_DOC_ID_IDX ON EPTO_EMPL_SCHEDULED_TIME_OFF_T(DOCUMENT_ID);

DROP TABLE IF EXISTS `EPTO_EMPL_SCHEDULED_TIME_OFF_S`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_EMPL_SCHEDULED_TIME_OFF_S` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

DROP TABLE IF EXISTS `EPTO_PS_CHANGE_T`;
CREATE TABLE `EPTO_PS_CHANGE_T` (
	PS_CHANGE_PSEUDO_ID BIGINT(19) NOT NULL,
    EMPLID VARCHAR(50) NOT NULL,
    EMPL_RCD DECIMAL(2,0) NOT NULL,
    EMPL_STATUS VARCHAR(1) NOT NULL,
    STD_HOURS DECIMAL(2,0) NOT NULL,
    SERVICE_DT DATE NOT NULL,
    LEAVE_PERCENT DECIMAL(15,0) NOT NULL,
    REG_PERCENT DECIMAL(15,0) NOT NULL,
    EFFDT DATE NOT NULL,
	ACTIVE_IND DECIMAL(1,0) NOT NULL DEFAULT '1',
	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1',
    CONSTRAINT EPTO_PS_CHANGE_T_PK PRIMARY KEY(EMPLID, EMPL_RCD, EFFDT)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE INDEX EPTO_PS_CHANGE_EMPLID_IDX ON EPTO_PS_CHANGE_T(EMPLID);
CREATE INDEX EPTO_PS_CHANGE_EMPL_RCD_IDX ON EPTO_PS_CHANGE_T(EMPL_RCD);
CREATE INDEX EPTO_PS_CHANGE_EMPL_STATUS_IDX ON EPTO_PS_CHANGE_T(EMPL_STATUS);

DROP TABLE IF EXISTS `EPTO_TRANSFER_T`;
CREATE TABLE `EPTO_TRANSFER_T` (
	EPTO_TRANSFER_PSEUDO_KEY 		BIGINT(19) NOT NULL,
    EMPLID                  		VARCHAR(50) NOT NULL,
	MONTH							DECIMAL(2,0) NOT NULL,
    YEAR							DECIMAL(4,0) NOT NULL,
	DOCUMENT_ID VARCHAR(19) NULL, 
	PREVIOUS_DOCUMENT_ID VARCHAR(19) NULL,
	EFFDT DATE NOT NULL,
	ACTIVE_IND DECIMAL(1,0) NOT NULL DEFAULT '1',
	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1',
    CONSTRAINT EPTO_TRANSFER_T_PK PRIMARY KEY(EMPLID, MONTH, YEAR)
);

CREATE INDEX EPTO_TRANSFER_EMPLID_IDX ON EPTO_TRANSFER_T(EMPLID);
CREATE INDEX EPTO_TRANSFER_MONTH_IDX ON EPTO_TRANSFER_T(MONTH);
CREATE INDEX EPTO_TRANSFER_YEAR_IDX ON EPTO_TRANSFER_T(YEAR);

DROP TABLE IF EXISTS `EPTO_EMPL_OVERRIDE_ROW_T`;
CREATE TABLE `EPTO_EMPL_OVERRIDE_ROW_T` (
    EMPL_OVR_ROW_PSEUDO_KEY DECIMAL(15,0) NOT NULL,
    EMPL_OVR_PSEUDO_KEY     DECIMAL(15,0) NOT NULL,
    MAX_CARRYOVER           DECIMAL(5,0) NULL,
    MAX_TAKEN               DECIMAL(5,0) NULL,
    MAX_TRANSFER            DECIMAL(5,0) NULL,
	FLEX_SCHEDULE			DECIMAL(1,0) NOT NULL,
    DOCUMENT_ID             VARCHAR(14) NULL,
    FMLA_OVERRIDE           DECIMAL(1,0) NOT NULL,
    INJ_OVERRIDE            DECIMAL(1,0) NOT NULL,
    MIL_OVERRIDE            DECIMAL(1,0) NOT NULL,
    EFFDT DATE NOT NULL,
	ACTIVE_IND DECIMAL(1,0) NOT NULL DEFAULT '1',
	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1',
    CONSTRAINT EMPL_OVR_ROW_PK PRIMARY KEY(EMPL_OVR_ROW_PSEUDO_KEY)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE INDEX EMPL_OVR_ROW_DOC_ID_IDX ON EPTO_EMPL_OVERRIDE_ROW_T(DOCUMENT_ID);
CREATE INDEX EMPL_OVR_ROW_EMPL_OVR_IDX ON EPTO_EMPL_OVERRIDE_ROW_T(EMPL_OVR_PSEUDO_KEY);

DROP TABLE IF EXISTS `EPTO_EMPL_OVERRIDE_T`;
CREATE TABLE `EPTO_EMPL_OVERRIDE_T` (
    EMPL_OVR_PSEUDO_KEY     BIGINT(19) NOT NULL,
    EMPLID                  VARCHAR(50) NOT NULL,
    EXPIRATION_DATE         DATE NULL,
    DOCUMENT_ID             VARCHAR(14) NULL,
    PREVIOUS_DOCUMENT_ID    VARCHAR(14) NULL,
    EFFDT DATE NOT NULL,
	ACTIVE_IND DECIMAL(1,0) NOT NULL DEFAULT '1',
	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1',
    CONSTRAINT EMPL_OVR_PK PRIMARY KEY(EMPL_OVR_PSEUDO_KEY, DOCUMENT_ID)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE INDEX EMPL_OVR_PSK_IDX ON EPTO_EMPL_OVERRIDE_T(EMPL_OVR_PSEUDO_KEY);
CREATE INDEX EMPL_OVR_DOC_ID_IDX ON EPTO_EMPL_OVERRIDE_T(DOCUMENT_ID);

DROP TABLE IF EXISTS `EPTO_EMPL_OVERRIDE_S`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_EMPL_OVERRIDE_S` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;
    
DROP TABLE IF EXISTS `EPTO_REPORTING_HIERARCHY_T`;
CREATE TABLE `EPTO_REPORTING_HIERARCHY_T`(
	REPORTING_HIERARCHY_PSEUDO_KEY BIGINT(19) NOT NULL,
	POSITION_NBR VARCHAR(50) NOT NULL,
    EMPLID VARCHAR(50) NOT NULL,
    EMPL_RCD DECIMAL(2,0) NOT NULL,
    EMPL_STATUS VARCHAR(1) NOT NULL,
	CAMPUS VARCHAR(50) NOT NULL,
	DEPTID VARCHAR(50) NOT NULL,
	EFFDT DATE NOT NULL,
	ACTIVE_IND DECIMAL(1,0) NOT NULL DEFAULT '1',
	TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	OBJ_ID VARCHAR(36) NOT NULL,
	VER_NBR DECIMAL(8,0) NOT NULL DEFAULT '1'
);
CREATE INDEX EMPL_REP_PSN_IDX ON EPTO_REPORTING_HIERARCHY_T(POSITION_NBR);
CREATE INDEX EMPL_REP_EMP_ID_IDX ON EPTO_REPORTING_HIERARCHY_T(EMPLID);

DROP TABLE IF EXISTS `EPTO_REPORTING_HIERARCHY_T`;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `EPTO_REPORTING_HIERARCHY_T` (
  `ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2000 DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;