package edu.iu.uis.hr.tk.rule.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:42 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;
import java.util.Date;

import edu.iu.uis.hr.EffectiveDatedObject;
import edu.iu.uis.hr.EffectiveSequencedObject;
import edu.iu.uis.hr.EffectiveStatusedObject;
import edu.iu.uis.hr.Timestamp;
import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractGracePeriodRule extends AbstractPersistentDatabaseEntity implements EffectiveDatedObject, EffectiveSequencedObject, EffectiveStatusedObject {
	private Date effectiveDate;
	private BigDecimal effectiveSequence;
	private boolean active;
	private BigDecimal graceMinutes;
	private BigDecimal hourFactor;
	private String userUniversityId;
	private Timestamp timestamp;

	public AbstractGracePeriodRule() {
		super();
	}

	public Date getEffectiveDate() {
		return effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public BigDecimal getEffectiveSequence() {
		return effectiveSequence;
	}

	public void setEffectiveSequence(BigDecimal effectiveSequence) {
		this.effectiveSequence = effectiveSequence;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public BigDecimal getGraceMinutes() {
		return graceMinutes;
	}

	public void setGraceMinutes(BigDecimal graceMinutes) {
		this.graceMinutes = graceMinutes;
	}

	public BigDecimal getHourFactor() {
		return hourFactor;
	}

	public void setHourFactor(BigDecimal hourFactor) {
		this.hourFactor = hourFactor;
	}

	public String getUserUniversityId() {
		return userUniversityId;
	}

	public void setUserUniversityId(String userUniversityId) {
		this.userUniversityId = userUniversityId;
	}

	public Timestamp getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Timestamp timestamp) {
		this.timestamp = timestamp;
	}

}