package edu.iu.uis.hr.tk.job.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:42 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;

import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractEarningsDistribution extends AbstractPersistentDatabaseEntity {
	private String earnCode;
	private BigDecimal distributionPercent;
	private Job job;

	public AbstractEarningsDistribution() {
		super();
	}

	public Job getJob() {
		return job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public String getEarnCode() {
		return earnCode;
	}

	public void setEarnCode(String earnCode) {
		this.earnCode = earnCode;
	}

	public BigDecimal getDistributionPercent() {
		return distributionPercent;
	}

	public void setDistributionPercent(BigDecimal distributionPercent) {
		this.distributionPercent = distributionPercent;
	}

}