package edu.iu.uis.hr.tk.timesheet.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:43 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.util.Collection;
import java.util.Date;

import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractDocumentHeader extends AbstractPersistentDatabaseEntity {
	private String documentId;
	private String universityId;
	private Date payEndDate;
	private String documentStatus;
	private DocumentLock documentLock;
	private Collection timeBlocks;

	public AbstractDocumentHeader() {
		super();
	}

	public DocumentLock getDocumentLock() {
		return documentLock;
	}

	public void setDocumentLock(DocumentLock documentLock) {
		this.documentLock = documentLock;
	}

	public Collection getTimeBlocks() {
		return timeBlocks;
	}

	public void setTimeBlocks(Collection timeBlocks) {
		if (timeBlocks != null) {
			this.timeBlocks = timeBlocks;
		}
	}

	public String getDocumentId() {
		return documentId;
	}

	public void setDocumentId(String documentId) {
		this.documentId = documentId;
	}

	public String getUniversityId() {
		return universityId;
	}

	public void setUniversityId(String universityId) {
		this.universityId = universityId;
	}

	public Date getPayEndDate() {
		return payEndDate;
	}

	public void setPayEndDate(Date payEndDate) {
		this.payEndDate = payEndDate;
	}

	public String getDocumentStatus() {
		return documentStatus;
	}

	public void setDocumentStatus(String documentStatus) {
		this.documentStatus = documentStatus;
	}

}