package edu.iu.uis.hr.tk.timesheet.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:43 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.util.Date;

import edu.iu.uis.hr.Timestamp;
import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractDailyNotification extends AbstractPersistentDatabaseEntity {
	private String documentId;
	private String universityId;
	private Date payEndDate;
	private String modifiedByUniversityId;
	private Timestamp timestamp;

	
	public AbstractDailyNotification() {
		super();
	}

	public String getDocumentId() {
		return documentId;
	}

	public void setDocumentId(String documentId) {
		this.documentId = documentId;
	}

	public String getUniversityId() {
		return universityId;
	}

	public void setUniversityId(String universityId) {
		this.universityId = universityId;
	}

	public Date getPayEndDate() {
		return payEndDate;
	}

	public void setPayEndDate(Date payEndDate) {
		this.payEndDate = payEndDate;
	}

	public String getModifiedByUniversityId() {
		return modifiedByUniversityId;
	}

	public void setModifiedByUniversityId(String modifiedByUniversityId) {
		this.modifiedByUniversityId = modifiedByUniversityId;
	}

	public Timestamp getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Timestamp timestamp) {
		this.timestamp = timestamp;
	}


}