package org.kuali.hr.time.mobile.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-11-22T12:37:54.993+05:30
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://service.mobile.time.hr.kuali.org/", name = "TkMobileService")
@XmlSeeAlso({ObjectFactory.class})
public interface TkMobileService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getClockEntryInfo", targetNamespace = "http://service.mobile.time.hr.kuali.org/", className = "org.kuali.hr.time.mobile.service.GetClockEntryInfo")
    @WebMethod
    @ResponseWrapper(localName = "getClockEntryInfoResponse", targetNamespace = "http://service.mobile.time.hr.kuali.org/", className = "org.kuali.hr.time.mobile.service.GetClockEntryInfoResponse")
    public java.lang.String getClockEntryInfo(
        @WebParam(name = "principalId", targetNamespace = "")
        java.lang.String principalId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addClockAction", targetNamespace = "http://service.mobile.time.hr.kuali.org/", className = "org.kuali.hr.time.mobile.service.AddClockAction")
    @WebMethod
    @ResponseWrapper(localName = "addClockActionResponse", targetNamespace = "http://service.mobile.time.hr.kuali.org/", className = "org.kuali.hr.time.mobile.service.AddClockActionResponse")
    public org.kuali.hr.time.mobile.service.HashMap addClockAction(
        @WebParam(name = "principalId", targetNamespace = "")
        java.lang.String principalId,
        @WebParam(name = "assignmentKey", targetNamespace = "")
        java.lang.String assignmentKey,
        @WebParam(name = "clockAction", targetNamespace = "")
        java.lang.String clockAction
    );
}
