DELETE FROM HR_HOLIDAY_CALENDAR_T WHERE HR_HOLIDAY_CALENDAR_ID = '1000';

INSERT INTO HR_HOLIDAY_CALENDAR_T (HR_HOLIDAY_CALENDAR_ID, HOLIDAY_CALENDAR_GROUP, DESCR, LOCATION, OBJ_ID, VER_NBR, ACTIVE) VALUES ('1000', 'REG', 'Test Description', NULL, UUID(), '1', 'Y');