DROP TABLE IF EXISTS `tk_dept_lunch_rl_t`;

CREATE TABLE `tk_dept_lunch_rl_t` (
`DEPT_LUNCH_RULE_ID` BIGINT(19) NOT NULL,
`DEPTID` VARCHAR(10),
`WORK_AREA_ID` DECIMAL(10,0),
`PRINCIPAL_ID` VARCHAR(10) NOT NULL DEFAULT '',
`JOB_NUMBER` DECIMAL(3,0),
`EFFDT` DATE NOT NULL,
`EFF_STATUS` VARCHAR(1),
`REQUIRED_CLOCK_FL` VARCHAR(3),
`MAX_MINS` DECIMAL(2),
`USER_PRINCIPAL_ID` VARCHAR(10),
`ACTIVE_IND` VARCHAR(1) NOT NULL DEFAULT '',
`TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`OBJ_ID` VARCHAR(36) NOT NULL,
`VER_NBR` DECIMAL(8,0) NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `tk_dept_lunch_rl_s` (
  ID bigint(19) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID)
) ENGINE=MyISAM AUTO_INCREMENT=2078 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;