package edu.iu.uis.hr.tk.employee.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:42 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;
import java.util.Date;

import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractLeaveAccrual extends AbstractPersistentDatabaseEntity {
	private String universityId;
	private BigDecimal employeeRecord;
	private String company;
	private String planType;
	private Date accrualProcessDate;
	private BigDecimal carryoverHours;
	private BigDecimal earnedYearToDateHours;
	private BigDecimal takenYearToDateHours;
	private BigDecimal adjustYearToDateHours;
	private BigDecimal boughtYearToDateHours;
	private BigDecimal soldYearToDateHours;
	private BigDecimal takenUnprocessedHours;
	private BigDecimal adjustUnprocessedHours;
	private BigDecimal boughtUnprocessedHours;
	private BigDecimal soldUnprocessedHours;

	public AbstractLeaveAccrual() {
		super();
	}

	public String getUniversityId() {
		return universityId;
	}

	public void setUniversityId(String universityId) {
		this.universityId = universityId;
	}

	public BigDecimal getEmployeeRecord() {
		return employeeRecord;
	}

	public void setEmployeeRecord(BigDecimal employeeRecord) {
		this.employeeRecord = employeeRecord;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getPlanType() {
		return planType;
	}

	public void setPlanType(String planType) {
		this.planType = planType;
	}

	public Date getAccrualProcessDate() {
		return accrualProcessDate;
	}

	public void setAccrualProcessDate(Date accrualProcessDate) {
		this.accrualProcessDate = accrualProcessDate;
	}

	public BigDecimal getCarryoverHours() {
		return carryoverHours;
	}

	public void setCarryoverHours(BigDecimal carryoverHours) {
		this.carryoverHours = carryoverHours;
	}

	public BigDecimal getEarnedYearToDateHours() {
		return earnedYearToDateHours;
	}

	public void setEarnedYearToDateHours(BigDecimal earnedYearToDateHours) {
		this.earnedYearToDateHours = earnedYearToDateHours;
	}

	public BigDecimal getTakenYearToDateHours() {
		return takenYearToDateHours;
	}

	public void setTakenYearToDateHours(BigDecimal takenYearToDateHours) {
		this.takenYearToDateHours = takenYearToDateHours;
	}

	public BigDecimal getAdjustYearToDateHours() {
		return adjustYearToDateHours;
	}

	public void setAdjustYearToDateHours(BigDecimal adjustYearToDateHours) {
		this.adjustYearToDateHours = adjustYearToDateHours;
	}

	public BigDecimal getBoughtYearToDateHours() {
		return boughtYearToDateHours;
	}

	public void setBoughtYearToDateHours(BigDecimal boughtYearToDateHours) {
		this.boughtYearToDateHours = boughtYearToDateHours;
	}

	public BigDecimal getSoldYearToDateHours() {
		return soldYearToDateHours;
	}

	public void setSoldYearToDateHours(BigDecimal soldYearToDateHours) {
		this.soldYearToDateHours = soldYearToDateHours;
	}

	public BigDecimal getTakenUnprocessedHours() {
		return takenUnprocessedHours;
	}

	public void setTakenUnprocessedHours(BigDecimal takenUnprocessedHours) {
		this.takenUnprocessedHours = takenUnprocessedHours;
	}

	public BigDecimal getAdjustUnprocessedHours() {
		return adjustUnprocessedHours;
	}

	public void setAdjustUnprocessedHours(BigDecimal adjustUnprocessedHours) {
		this.adjustUnprocessedHours = adjustUnprocessedHours;
	}

	public BigDecimal getBoughtUnprocessedHours() {
		return boughtUnprocessedHours;
	}

	public void setBoughtUnprocessedHours(BigDecimal boughtUnprocessedHours) {
		this.boughtUnprocessedHours = boughtUnprocessedHours;
	}

	public BigDecimal getSoldUnprocessedHours() {
		return soldUnprocessedHours;
	}

	public void setSoldUnprocessedHours(BigDecimal soldUnprocessedHours) {
		this.soldUnprocessedHours = soldUnprocessedHours;
	}

}