package edu.iu.uis.hr.tk.extract.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:42 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;
import java.util.Date;

import edu.iu.uis.hr.Timestamp;
import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractPayrollInterface extends AbstractPersistentDatabaseEntity {
	private String company;
	private String paygroup;
	private Date payEndDate;
	private boolean offCycle;
	private String universityId;
	private BigDecimal employeeRecord;
	private Date earnsBeginDate;
	private Date earnsEndDate;
	private String earnCode;
	private BigDecimal order;
	private String chartOfAccounts;
	private String account;
	private String subAccount;
	private String object;
	private String subObject;
	private String project;
	private String organizationReferenceId;
	private BigDecimal pageNumber;
	private BigDecimal lineNumber;
	private BigDecimal employeeRecordOther;
	private BigDecimal additionalPayLineNumber;
	private BigDecimal additionalSequence;
	private BigDecimal hoursForPeriod;
	private BigDecimal rate;
	private BigDecimal amount;
	private BigDecimal percentage;
	private String payfundInterfaceId;
	private String payfundStatus;
	private String createdOprId;
	private Timestamp dateTimeCreated;
	private String lastUpdateOprId;
	private Timestamp lastUpdateDateTime;
	private String payfundProcessMessage;
	private String billDepartment;
	private String voucherTableCode;
	private boolean grossup;
	private String adjustmentVoucherType;
	private String description254;

	public AbstractPayrollInterface() {
		super();
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getPaygroup() {
		return paygroup;
	}

	public void setPaygroup(String paygroup) {
		this.paygroup = paygroup;
	}

	public Date getPayEndDate() {
		return payEndDate;
	}

	public void setPayEndDate(Date payEndDate) {
		this.payEndDate = payEndDate;
	}

	public boolean isOffCycle() {
		return offCycle;
	}

	public void setOffCycle(boolean offCycle) {
		this.offCycle = offCycle;
	}

	public String getUniversityId() {
		return universityId;
	}

	public void setUniversityId(String universityId) {
		this.universityId = universityId;
	}

	public BigDecimal getEmployeeRecord() {
		return employeeRecord;
	}

	public void setEmployeeRecord(BigDecimal employeeRecord) {
		this.employeeRecord = employeeRecord;
	}

	public Date getEarnsBeginDate() {
		return earnsBeginDate;
	}

	public void setEarnsBeginDate(Date earnsBeginDate) {
		this.earnsBeginDate = earnsBeginDate;
	}

	public Date getEarnsEndDate() {
		return earnsEndDate;
	}

	public void setEarnsEndDate(Date earnsEndDate) {
		this.earnsEndDate = earnsEndDate;
	}

	public String getEarnCode() {
		return earnCode;
	}

	public void setEarnCode(String earnCode) {
		this.earnCode = earnCode;
	}

	public BigDecimal getOrder() {
		return order;
	}

	public void setOrder(BigDecimal order) {
		this.order = order;
	}

	public String getChartOfAccounts() {
		return chartOfAccounts;
	}

	public void setChartOfAccounts(String chartOfAccounts) {
		this.chartOfAccounts = chartOfAccounts;
	}

	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getSubAccount() {
		return subAccount;
	}

	public void setSubAccount(String subAccount) {
		this.subAccount = subAccount;
	}

	public String getObject() {
		return object;
	}

	public void setObject(String object) {
		this.object = object;
	}

	public String getSubObject() {
		return subObject;
	}

	public void setSubObject(String subObject) {
		this.subObject = subObject;
	}

	public String getProject() {
		return project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public String getOrganizationReferenceId() {
		return organizationReferenceId;
	}

	public void setOrganizationReferenceId(String organizationReferenceId) {
		this.organizationReferenceId = organizationReferenceId;
	}

	public BigDecimal getPageNumber() {
		return pageNumber;
	}

	public void setPageNumber(BigDecimal pageNumber) {
		this.pageNumber = pageNumber;
	}

	public BigDecimal getLineNumber() {
		return lineNumber;
	}

	public void setLineNumber(BigDecimal lineNumber) {
		this.lineNumber = lineNumber;
	}

	public BigDecimal getEmployeeRecordOther() {
		return employeeRecordOther;
	}

	public void setEmployeeRecordOther(BigDecimal employeeRecordOther) {
		this.employeeRecordOther = employeeRecordOther;
	}

	public BigDecimal getAdditionalPayLineNumber() {
		return additionalPayLineNumber;
	}

	public void setAdditionalPayLineNumber(BigDecimal additionalPayLineNumber) {
		this.additionalPayLineNumber = additionalPayLineNumber;
	}

	public BigDecimal getAdditionalSequence() {
		return additionalSequence;
	}

	public void setAdditionalSequence(BigDecimal additionalSequence) {
		this.additionalSequence = additionalSequence;
	}

	public BigDecimal getHoursForPeriod() {
		return hoursForPeriod;
	}

	public void setHoursForPeriod(BigDecimal hoursForPeriod) {
		this.hoursForPeriod = hoursForPeriod;
	}

	public BigDecimal getRate() {
		return rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getPercentage() {
		return percentage;
	}

	public void setPercentage(BigDecimal percentage) {
		this.percentage = percentage;
	}

	public String getPayfundInterfaceId() {
		return payfundInterfaceId;
	}

	public void setPayfundInterfaceId(String payfundInterfaceId) {
		this.payfundInterfaceId = payfundInterfaceId;
	}

	public String getPayfundStatus() {
		return payfundStatus;
	}

	public void setPayfundStatus(String payfundStatus) {
		this.payfundStatus = payfundStatus;
	}

	public String getCreatedOprId() {
		return createdOprId;
	}

	public void setCreatedOprId(String createdOprId) {
		this.createdOprId = createdOprId;
	}

	public Timestamp getDateTimeCreated() {
		return dateTimeCreated;
	}

	public void setDateTimeCreated(Timestamp dateTimeCreated) {
		this.dateTimeCreated = dateTimeCreated;
	}

	public String getLastUpdateOprId() {
		return lastUpdateOprId;
	}

	public void setLastUpdateOprId(String lastUpdateOprId) {
		this.lastUpdateOprId = lastUpdateOprId;
	}

	public Timestamp getLastUpdateDateTime() {
		return lastUpdateDateTime;
	}

	public void setLastUpdateDateTime(Timestamp lastUpdateDateTime) {
		this.lastUpdateDateTime = lastUpdateDateTime;
	}

	public String getPayfundProcessMessage() {
		return payfundProcessMessage;
	}

	public void setPayfundProcessMessage(String payfundProcessMessage) {
		this.payfundProcessMessage = payfundProcessMessage;
	}

	public String getBillDepartment() {
		return billDepartment;
	}

	public void setBillDepartment(String billDepartment) {
		this.billDepartment = billDepartment;
	}

	public String getVoucherTableCode() {
		return voucherTableCode;
	}

	public void setVoucherTableCode(String voucherTableCode) {
		this.voucherTableCode = voucherTableCode;
	}

	public boolean isGrossup() {
		return grossup;
	}

	public void setGrossup(boolean grossup) {
		this.grossup = grossup;
	}

	public String getAdjustmentVoucherType() {
		return adjustmentVoucherType;
	}

	public void setAdjustmentVoucherType(String adjustmentVoucherType) {
		this.adjustmentVoucherType = adjustmentVoucherType;
	}

	public String getDescription254() {
		return description254;
	}

	public void setDescription254(String description254) {
		this.description254 = description254;
	}

}