package edu.iu.uis.hr.tk.extract.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:43 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;
import java.util.Date;

import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;

public abstract class AbstractTkPayrollInterface extends AbstractPersistentDatabaseEntity {
	private String company;
	private String paygroup;
	private Date payEndDate;
	private String universityId;
	private BigDecimal employeeRecord;
	private Date earnsBeginDate;
	private Date earnsEndDate;
	private String earnCode;
	private String chartOfAccounts;
	private String account;
	private String subAccount;
	private String object;
	private String subObject;
	private String project;
	private String organizationReferenceId;
	private BigDecimal hoursForPeriod;
	private String payfundInterfaceId;

	public AbstractTkPayrollInterface() {
		super();
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getPaygroup() {
		return paygroup;
	}

	public void setPaygroup(String paygroup) {
		this.paygroup = paygroup;
	}

	public Date getPayEndDate() {
		return payEndDate;
	}

	public void setPayEndDate(Date payEndDate) {
		this.payEndDate = payEndDate;
	}

	public String getUniversityId() {
		return universityId;
	}

	public void setUniversityId(String universityId) {
		this.universityId = universityId;
	}

	public BigDecimal getEmployeeRecord() {
		return employeeRecord;
	}

	public void setEmployeeRecord(BigDecimal employeeRecord) {
		this.employeeRecord = employeeRecord;
	}

	public Date getEarnsBeginDate() {
		return earnsBeginDate;
	}

	public void setEarnsBeginDate(Date earnsBeginDate) {
		this.earnsBeginDate = earnsBeginDate;
	}

	public Date getEarnsEndDate() {
		return earnsEndDate;
	}

	public void setEarnsEndDate(Date earnsEndDate) {
		this.earnsEndDate = earnsEndDate;
	}

	public String getEarnCode() {
		return earnCode;
	}

	public void setEarnCode(String earnCode) {
		this.earnCode = earnCode;
	}

	public String getChartOfAccounts() {
		return chartOfAccounts;
	}

	public void setChartOfAccounts(String chartOfAccounts) {
		this.chartOfAccounts = chartOfAccounts;
	}

	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getSubAccount() {
		return subAccount;
	}

	public void setSubAccount(String subAccount) {
		this.subAccount = subAccount;
	}

	public String getObject() {
		return object;
	}

	public void setObject(String object) {
		this.object = object;
	}

	public String getSubObject() {
		return subObject;
	}

	public void setSubObject(String subObject) {
		this.subObject = subObject;
	}

	public String getProject() {
		return project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public String getOrganizationReferenceId() {
		return organizationReferenceId;
	}

	public void setOrganizationReferenceId(String organizationReferenceId) {
		this.organizationReferenceId = organizationReferenceId;
	}

	public BigDecimal getHoursForPeriod() {
		return hoursForPeriod;
	}

	public void setHoursForPeriod(BigDecimal hoursForPeriod) {
		this.hoursForPeriod = hoursForPeriod;
	}

	public String getPayfundInterfaceId() {
		return payfundInterfaceId;
	}

	public void setPayfundInterfaceId(String payfundInterfaceId) {
		this.payfundInterfaceId = payfundInterfaceId;
	}

}