package edu.iu.uis.hr.tk.job.funding.entity;

/*******************************************************************************
 * DO NOT MODIFY THIS FILE - MODIFY THE MODEL AND REGENERATE
 * Generated on: Fri Dec 28 10:16:42 EST 2007
 * Generated by: HR/bdo version 1.52
/******************************************************************************/

import java.math.BigDecimal;

import edu.iu.uis.hr.entity.AbstractPersistentDatabaseEntity;
import edu.iu.uis.hr.tk.job.entity.Job;

public abstract class AbstractAssignment extends AbstractPersistentDatabaseEntity {
	private String earnCode;
	private BigDecimal additionalSequence;
	private BigDecimal order;
	private String chartOfAccounts;
	private String account;
	private String subAccount;
	private String object;
	private String subObject;
	private String project;
	private BigDecimal workArea;
	private BigDecimal task;
	private String organizationReferenceId;
	private BigDecimal percent;
	private Job job;

	public AbstractAssignment() {
		super();
	}

	public Job getJob() {
		return job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public String getEarnCode() {
		return earnCode;
	}

	public void setEarnCode(String earnCode) {
		this.earnCode = earnCode;
	}

	public BigDecimal getAdditionalSequence() {
		return additionalSequence;
	}

	public void setAdditionalSequence(BigDecimal additionalSequence) {
		this.additionalSequence = additionalSequence;
	}

	public BigDecimal getOrder() {
		return order;
	}

	public void setOrder(BigDecimal order) {
		this.order = order;
	}

	public String getChartOfAccounts() {
		return chartOfAccounts;
	}

	public void setChartOfAccounts(String chartOfAccounts) {
		this.chartOfAccounts = chartOfAccounts;
	}

	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getSubAccount() {
		return subAccount;
	}

	public void setSubAccount(String subAccount) {
		this.subAccount = subAccount;
	}

	public String getObject() {
		return object;
	}

	public void setObject(String object) {
		this.object = object;
	}

	public String getSubObject() {
		return subObject;
	}

	public void setSubObject(String subObject) {
		this.subObject = subObject;
	}

	public String getProject() {
		return project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public BigDecimal getWorkArea() {
		return workArea;
	}

	public void setWorkArea(BigDecimal workArea) {
		this.workArea = workArea;
	}

	public BigDecimal getTask() {
		return task;
	}

	public void setTask(BigDecimal task) {
		this.task = task;
	}

	public String getOrganizationReferenceId() {
		return organizationReferenceId;
	}

	public void setOrganizationReferenceId(String organizationReferenceId) {
		this.organizationReferenceId = organizationReferenceId;
	}

	public BigDecimal getPercent() {
		return percent;
	}

	public void setPercent(BigDecimal percent) {
		this.percent = percent;
	}

}